### PR TITLE
fix session range comparision expression

### LINKED ISSUE #810: Unbalanced parentheses in a session are considered an error
**Describe what's wrong**
Unbalanced parentheses in a session are considered an error when definitions are being loaded from the store.

**How to reproduce**
```
CREATE STREAM speed (speed float64)
```

```
CREATE MATERIALIZED VIEW v AS
SELECT
  window_start AS start, window_end AS end, avg(speed)
FROM
  session(speed, 1m, [speed > 50,speed < 50))
GROUP BY
  window_start, window_end
```
```
SHOW CREATE v
```

**Error message and/or stacktrace**
```
Query id: efad8ca0-5950-433c-a871-4367a0ef7680


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 1.5.12):
Code: 62. DB::Exception: Received from localhost:8463. DB::Exception: Syntax error (in file /home/kambis/proton-data/store/90f36a1a-9142-4f7c-aac9-42c4c00ebd90/v.sql): failed at position 521 (')') (line 12, col 94): ))
GROUP BY
  window_start, window_end
. Expected end of query. (SYNTAX_ERROR)
```
This is the content of v.sql
```
ATTACH MATERIALIZED VIEW _ UUID '4354ad70-167f-4f43-8963-b42ae2e93775' INTO INNER UUID '40909870-702c-4d18-a9db-db6745285516'
(
  `start` datetime64(3, 'UTC'),
  `end` datetime64(3, 'UTC'),
  `avg(speed)` float64,
  `_tp_time` datetime64(3, 'UTC') DEFAULT now64(3, 'UTC') CODEC(DoubleDelta, LZ4),
  INDEX _tp_time_index _tp_time TYPE minmax GRANULARITY 2
) AS
SELECT
  window_start AS start, window_end AS end, avg(speed)
FROM
  session(default.speed, 1m, [speed > 50 AS __tp_session_start,speed < 50 AS __tp_session_end))
GROUP BY
  window_start, window_end
```
and the corresponding line 12 is
```
  session(default.speed, 1m, [speed > 50 AS __tp_session_start,speed < 50 AS __tp_session_end))                                                                                                    
                                                                                             ^
                                                                                          col 94
```

### PR DESCRIPTION
**Pull request by yl-lisen**
Fix #810

### CODE REVIEW

File: src/TableFunctions/TableFunctionSession.cpp [hunk 1]
```diff
@@ -32,12 +32,43 @@ void TableFunctionSession::parseArguments(const ASTPtr & func_ast, ContextPtr co
...
+        args[3] = std::make_shared<ASTLiteral>(true);
+        args[4] = std::make_shared<ASTLiteral>(true);
+        args[5] = std::make_shared<ASTLiteral>(false);
+        args[6] = std::make_shared<ASTLiteral>(true);
+    }
+    assert(args[3] && args[4] && args[5] && args[6]);
+
+    /// They may be used in aggregation transform, so set an internal alias for them
+    args[3]->setAlias(ProtonConsts::STREAMING_SESSION_START);
+    args[5]->setAlias(ProtonConsts::STREAMING_SESSION_END);
```
Comment (yokofly) [inline src/TableFunctions/TableFunctionSession.cpp:62]: is possible the input only 4 args? and args[5] nullptr?

Comment (yokofly) [reply src/TableFunctions/TableFunctionSession.cpp:62]: I expected thoes assert to be obvious if condition check, and add some incorrect input tests.
otherwise the release versions not build assert.

File: src/Parsers/Streaming/ASTSessionRangeComparision.cpp [hunk 2]
```diff
@@ -21,26 +30,24 @@ void ASTSessionRangeComparision::updateTreeHashImpl(SipHash & hash_state) const
...
-        children[1]->appendColumnName(ostr);
-        writeString((end_with_inclusion ? "]" : ")"), ostr);
-    }
+    assert(children.size() == 2);
+
+    writeString((start_with_inclusion ? "[" : "("), ostr);
+    children[0]->appendColumnName(ostr);
+    writeString(", ", ostr);
+    children[1]->appendColumnName(ostr);
+    writeString((end_with_inclusion ? "]" : ")"), ostr);
```
Comment (yokofly) [inline src/Parsers/Streaming/ASTSessionRangeComparision.cpp:50]: why we remove this condition check? is there any reason here?

**Review by yokofly — COMMENTED** [review]
we are missing tests about incorrect input with window function, thus I expected at least keep the old if condition check still instead assert.

File: src/Parsers/Streaming/ASTSessionRangeComparision.cpp (hunk 2 above)
Comment (yl-lisen) [reply src/Parsers/Streaming/ASTSessionRangeComparision.cpp:50]: it has only two elements, guaranteed in `ParserSessionRangeComparisonExpressionIfPossible::parseImpl`

File: src/TableFunctions/TableFunctionSession.cpp (hunk 1 above)
Comment (yl-lisen) [reply src/TableFunctions/TableFunctionSession.cpp:62]: > is possible the input only 4 args? and args[5] nullptr?

No, we extracted arguments and populated with full argument numbers in `TableFunctionSession::checkAndExtractArguments`

Comment (yokofly) [reply src/TableFunctions/TableFunctionSession.cpp:62]: if those `if branch` is redundant, let's add some tests?

**Review by yokofly — APPROVED** [review]

**Comment by yokofly** [comment]
waiting CI

**Comment by yl-lisen** [comment]
flakey stateless test case `00301_csv` failed.
