### PR TITLE
Fix append time regression

### LINKED ISSUE #223: _tp_append_time column is 0
```sql
drop stream if exists test1;
create stream if not exists test1(id int, value int);
insert into test1(id, value) values(1, 2);
insert into test1(id, value) values(3, 2);
insert into test1(id, value) values(4, 2);
```
If you use `select * , _tp_append_time from test1 where _tp_time > earliest_timestamp()
`,the _tp_append_time column has no value.
image
But if you specify the column you want select, it will work well.

image

### PR DESCRIPTION
**Pull request by chenziliang**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Close #223 

Please write user-readable short description of the changes:

### CODE REVIEW

File: src/Core/Block.cpp [hunk 1]
```diff
@@ -879,7 +879,9 @@ void Block::reorderColumnsInplace(const std::vector<UInt16> & positions)
         result.insert(std::move(target_col));
     }
 
-    swap(result);
+    /// Don't swap block.info
+    data.swap(result.data);
+    index_by_name.swap(result.index_by_name);
 }
```
Comment (yl-lisen) [inline src/Core/Block.cpp:885]: need apply same changes in another overload function `reorderColumnsInplace`

File: src/NativeLog/Record/Record.cpp [hunk 2]
```diff
@@ -135,13 +135,13 @@ RecordPtr Record::deserialize(const char * data, size_t size, const SchemaContex
         if (likely(record->codec() == DB::CompressionMethodByte::NONE))
         {
             DB::NativeReader reader(rb, DBMS_TCP_PROTOCOL_VERSION);
-            record->setBlock(reader.read());
+            record->setBlock(reader.read(), /*override_block_info=*/false);
```
Comment (yl-lisen) [inline src/NativeLog/Record/Record.cpp:138]: it seems that deserialized block will lose block info. Probably needs to fix. in future

Comment (chenziliang) [reply src/NativeLog/Record/Record.cpp:138]: So far we don't carry any information in block.info in a Record when serialization.
