### PR TITLE
try fix ci by pin python package requests version

### LINKED ISSUE #740: CI fail: smoke test fail in startup
**Describe what's wrong**

```
Traceback (most recent call last):
  File "/actions-runner/_work/proton/proton/tests/stream/ci_runner.py", line 491, in <module>
ci_runner starting: run_mode = github, loop = 1, logging_level=ERROR, test_retry = True, test_suite_timeout = 900, test_folders = test_stream_smoke starts
    raise Exception("Env docker compose up failure.")
Exception: Env docker compose up failure.
args_dict = {'run_mode': 'github', 'debug': False, 'test_folders': 'test_stream_smoke', 'test_suites': 'None', 'id': 'None', 'loop': 1, 'settings': 'redp,nativelog', 'cluster_query_route_mode': 'None', 'cluster_query_node': 'None', 'create_stream_shards': 'None', 'create_stream_replicas': 'None', 'no_retry': False, 'test_suite_timeout': 900, 'tmp': 'None'}
self._event.value = {'event_type': 'test_event', 'payload': {'detailed_type': 'status', 'details': 'start'}}
self._tag_value = {'version': '0.1', 'repo_name': 'proton', 'test_info': {'test_id': '36ba2294-17f5-11ef-a8e3-2b01b7dfa725', 'test_name': 'ci_runner', 'test_type': 'ci_smoke'}, 'build_info': {'build_type': 'address', 'pr_number': '739/merge', 'commit_sha': '607d321c31aab8736f33d6af2c1bb63cd83cae8f'}, 'run_time_info': {'os': 'Linux', 'platform': 'X64'}}
test_event_start sent
```

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by yokofly**
revert 95b9de83196c56623a6c55673acd6f7541b917c7

PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

### CODE REVIEW

File: src/Server/RestRouterHandlers/PingHandler.cpp [hunk 1]
```diff
@@ -84,7 +84,7 @@ void PingHandler::buildResponse(const Block & block, String & resp) const
 
     const auto & server_uuid = DB::ServerUUID::get();
 
-    server_info.set("uuid", DB::toString(server_uuid));
+    server_info.set("uuid", server_uuid != DB::UUIDHelpers::Nil ? DB::toString(server_uuid) : "Unknown");
```
Comment (chenziliang) [inline src/Server/RestRouterHandlers/PingHandler.cpp]: I think we shall not use Unknown

**Review by zliang-min — APPROVED** [review]
