### PR TITLE
Bugfix/issue 701 validate input has delta column for changelog output for view

### LINKED ISSUE #700: Streaming bidirectional join logical issue
**Describe what's wrong**

```
2024.05.12 19:30:58.957044 [ 10870 ] {b2b340ad-845d-45aa-b8d9-002ef3357cdd} <Error> executeQuery: Code: 11. DB::Exception: Position out of bound in Block::erase(), max position = 1: While executing StreamingJoinTransform. (POSITION_OUT_OF_BOUND) (version 1.5.7) (from [::ffff:10.3.44.18]:55320) (in query: select l.instrumentId from interesting_numbers_ledgers as l left join trade_summary_view as t on l.instrumentId = t.instrumentId)
2024.05.12 19:30:59.105564 [ 10870 ] {b2b340ad-845d-45aa-b8d9-002ef3357cdd} <Error> TCPHandler: Code: 11. DB::Exception: Position out of bound in Block::erase(), max position = 1: While executing StreamingJoinTransform. (POSITION_OUT_OF_BOUND), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x000000001aa3eef9 in /usr/bin/proton
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0x0000000010108fba in /usr/bin/proton
2. DB::Block::erase(unsigned long) @ 0x00000000153c3894 in /usr/bin/proton
3. void DB::Streaming::HashJoin::transformToOutputBlock<true>(DB::Block&) const @ 0x0000000016d6a2db in /usr/bin/proton
4. DB::Block DB::Streaming::HashJoin::joinBlockWithHashTable<true>(DB::Block&, std::__1::shared_ptr<DB::Streaming::HashBlocks>) @ 0x0000000016d698cd in /usr/bin/proton
5. DB::Streaming::HashJoin::insertLeftBlockAndJoin(DB::Block&) @ 0x0000000016b4e579 in /usr/bin/proton
6. DB::Streaming::JoinTransform::joinBidirectionally(std::__1::array<DB::Chunk, 2ul>) @ 0x0000000016e7ea08 in /usr/bin/proton
7. DB::Streaming::JoinTransform::doJoin(std::__1::array<DB::Chunk, 2ul>) @ 0x0000000016e7d9a4 in /usr/bin/proton
8. DB::Streaming::JoinTransform::work() @ 0x0000000016e7cad7 in /usr/bin/proton
9. DB::ExecutionThreadContext::executeTask() @ 0x00000000168f8fd7 in /usr/bin/proton
10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x00000000168eb55d in /usr/bin/proton
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long, DB::ExecuteMode)::$_0>(DB::PipelineExecutor::executeImpl(unsigned long, DB::ExecuteMode)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x00000000168ecde7 in /usr/bin/proton
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x00000000101a314f in /usr/bin/proton
13. void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x00000000101a5b8e in /usr/bin/proton
14. ? @ 0x00007f8b55d32609 in ?
15. clone @ 0x00007f8b55c47353 in ?
```

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

### LINKED ISSUE #701: Streaming inner join crash
**Describe what's wrong**

```
2024.05.12 19:31:30.035697 [ 48826 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.05.12 19:31:30.035808 [ 48826 ] {} <Fatal> BaseDaemon: (version 1.5.7, build id: A5A078F9B1BCC9C27A96032150BFA51DD94C0CC1, git hash: d9223fd759db45eadc375096162898a7117ca040) (from thread 17585) Received signal 11
2024.05.12 19:31:30.035837 [ 48826 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.05.12 19:31:30.035848 [ 48826 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2024.05.12 19:31:30.035864 [ 48826 ] {} <Fatal> BaseDaemon: Stack trace: 0x00000000168bc8d4 0x00000000168bc868 0x0000000016e7f3f5 0x0000000016e7ebbe 0x0000000016e7d9a4 0x0000000016e7cad7 0x00000000168f8fd7 0x00000000168eb55d 0x00000000168ecde7 0x00000000101a314f 0x00000000101a5b8e 0x00007f8b55d32609 0x00007f8b55c47353
2024.05.12 19:31:30.035873 [ 48826 ] {} <Fatal> BaseDaemon: ########################################
2024.05.12 19:31:30.035881 [ 48826 ] {} <Fatal> BaseDaemon: (version 1.5.7, build id: A5A078F9B1BCC9C27A96032150BFA51DD94C0CC1, git hash: d9223fd759db45eadc375096162898a7117ca040) (from thread 17585) (query_id: 2602c04a-34be-40b2-b69b-1dba71387156) (query: select l.instrumentId, t.instrumentId from interesting_numbers_ledgers as l join trade_summary_view as t on l.instrumentId = t.instrumentId) Received signal Segmentation fault (11)
2024.05.12 19:31:30.035889 [ 48826 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2024.05.12 19:31:30.035894 [ 48826 ] {} <Fatal> BaseDaemon: Stack trace: 0x00000000168bc8d4 0x00000000168bc868 0x0000000016e7f3f5 0x0000000016e7ebbe 0x0000000016e7d9a4 0x0000000016e7cad7 0x00000000168f8fd7 0x00000000168eb55d 0x00000000168ecde7 0x00000000101a314f 0x00000000101a5b8e 0x00007f8b55d32609 0x00007f8b55c47353
2024.05.12 19:31:30.037120 [ 48826 ] {} <Fatal> BaseDaemon: 3. DB::Chunk::checkNumRowsIsConsistent() @ 0x00000000168bc8d4 in /usr/bin/proton
2024.05.12 19:31:30.037145 [ 48826 ] {} <Fatal> BaseDaemon: 4. DB::Chunk::Chunk(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long) @ 0x00000000168bc868 in /usr/bin/proton
2024.05.12 19:31:30.037179 [ 48826 ] {} <Fatal> BaseDaemon: 5. void std::__1::allocator_traits<std::__1::allocator<std::__1::__list_node<DB::Chunk, void*>>>::construct[abi:v15000]<DB::Chunk, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>, unsigned long, void, void>(std::__1::allocator<std::__1::__list_node<DB::Chunk, void*>>&, DB::Chunk*, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&&, unsigned long&&) @ 0x0000000016e7f3f5 in /usr/bin/proton
2024.05.12 19:31:30.037193 [ 48826 ] {} <Fatal> BaseDaemon: 6. DB::Streaming::JoinTransform::joinBidirectionally(std::__1::array<DB::Chunk, 2ul>) @ 0x0000000016e7ebbe in /usr/bin/proton
2024.05.12 19:31:30.037207 [ 48826 ] {} <Fatal> BaseDaemon: 7. DB::Streaming::JoinTransform::doJoin(std::__1::array<DB::Chunk, 2ul>) @ 0x0000000016e7d9a4 in /usr/bin/proton
2024.05.12 19:31:30.037216 [ 48826 ] {} <Fatal> BaseDaemon: 8. DB::Streaming::JoinTransform::work() @ 0x0000000016e7cad7 in /usr/bin/proton
2024.05.12 19:31:30.037224 [ 48826 ] {} <Fatal> BaseDaemon: 9. DB::ExecutionThreadContext::executeTask() @ 0x00000000168f8fd7 in /usr/bin/proton
2024.05.12 19:31:30.037234 [ 48826 ] {} <Fatal> BaseDaemon: 10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x00000000168eb55d in /usr/bin/proton
2024.05.12 19:31:30.037251 [ 48826 ] {} <Fatal> BaseDaemon: 11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long, DB::ExecuteMode)::$_0>(DB::PipelineExecutor::executeImpl(unsigned long, DB::ExecuteMode)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) @ 0x00000000168ecde7 in /usr/bin/proton
2024.05.12 19:31:30.037267 [ 48826 ] {} <Fatal> BaseDaemon: 12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x00000000101a314f in /usr/bin/proton
2024.05.12 19:31:30.037280 [ 48826 ] {} <Fatal> BaseDaemon: 13. void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x00000000101a5b8e in /usr/bin/proton
2024.05.12 19:31:30.037292 [ 48826 ] {} <Fatal> BaseDaemon: 14. ? @ 0x00007f8b55d32609 in ?
2024.05.12 19:31:30.037300 [ 48826 ] {} <Fatal> BaseDaemon: 15. clone @ 0x00007f8b55c47353 in ?
```

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by yl-lisen**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:
This fix #700 and fix #701

### CODE REVIEW

File: src/Interpreters/Streaming/ChangelogQueryVisitor.cpp [hunk 1]
```diff
@@ -131,10 +131,10 @@ void ChangelogQueryVisitorMatcher::addDeltaColumn(ASTSelectQuery & select_query,
     if (!found_delta_col)
     {
         if (is_subquery)
-            /// Need add delta if _tp_delta is not present and the @p select_query is a subquery 
+            /// Need add delta if _tp_delta is not present and the \param select_query is a subquery (not top level select)
             select_expression_list->children.emplace_back(std::make_shared<ASTIdentifier>(ProtonConsts::RESERVED_DELTA_FLAG));
-        else if (query_info.force_emit_changelog)
-            throw Exception(ErrorCodes::NOT_IMPLEMENTED, "The query with emit changelog explicitly requires a `_tp_delta` in select list");
+        else
+            throw Exception(ErrorCodes::INCORRECT_QUERY, "The query with changelog output requires selecting the `_tp_delta` column explicitly");
```
Comment (chenziliang) [inline src/Interpreters/Streaming/ChangelogQueryVisitor.cpp:137]: Look like now when top select missing `_tp_delta`, we will report this exception as well. For example, `select l.instrumentId from interesting_numbers_base_data as l join trade_summary as t on l.instrumentId = t.instrumentId` failed by default and `CREATE VIEW interesting_numbers_base_data` failed as well.

Ideally `_tp_delta` will be added back by internal logic if it is required and users didn't explicitly select it. For top select, user doesn't have to select _tp_delta in which case the upsert scemantic shall be retained

Comment (yl-lisen) [reply src/Interpreters/Streaming/ChangelogQueryVisitor.cpp:137]: Yes, now explicitly select the "_tp_delta" column in the above scenario
Next stage: the behavior will be adjusted, for top select query it will always be "append only" semantics by default unless specified with "EMIT CHANGELOG"

**Review by chenziliang — APPROVED** [review]
