### PR TITLE
fix to_datetime64 parsing problem

### LINKED ISSUE #843: Serialization error existed in to_datetime64 function
Error will occur if we add time zone fraction in to_datetime64 function
```
timeplus-OptiPlex-7000 :) select to_datetime64('2022-12-30 13:44:17.00+08:00',2)

SELECT
  to_datetime64('2022-12-30 13:44:17.00+08:00', 2)

Query id: 27f6935a-8deb-4ece-a4d1-4339203048fe


0 rows in set. Elapsed: 220.572 sec. 

Received exception from server (version 1.6.1):
Code: 6. DB::Exception: Received from localhost:8463. DB::Exception: Cannot parse string '2022-12-30 13:44:17.00+08:00' as datetime64(2): syntax error at position 22 (parsed just '2022-12-30 13:44:17.00'). (CANNOT_PARSE_TEXT)
```

### PR DESCRIPTION
**Pull request by Jasmine-ge**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:
close #843

### CODE REVIEW

File: tests/queries_ported/0_stateless/02991_datetime_timezone.sql [hunk 1]
```diff
@@ -1,16 +1,18 @@
...
 SELECT t1, t2, t3 FROM Dates;
 
 DROP STREAM IF EXISTS Dates;
 
 CREATE stream Dates(t1 datetime64(3, 'Europe/London'), t2 datetime64(3, 'America/Vancouver'), t3 datetime64(3)) ENGINE = Memory();
 
-INSERT INTO Dates VALUES (to_time('6/9/2024 13:28','Europe/London'), to_time('6/9/2024 13:28','Europe/London'), to_time('6/9/2024 13:28','Europe/London'));
+INSERT INTO Dates VALUES (to_datetime64('2024-06-09 13:28:00.000',3 ,'Europe/London'), to_time('6/9/2024 13:28','Europe/London'), to_time('6/9/2024 13:28','Europe/London'));
 
 SELECT t1, t2, t3 FROM Dates;
```
Comment (yl-lisen) [inline tests/queries_ported/0_stateless/02991_datetime_timezone.sql]: don't modify original test case from community, you can cover it in new test case file

**Review by yl-lisen — APPROVED** [review]
