### PR TITLE
trymake `cmake ..` work in mac (x86 and m1)

### LINKED ISSUE #94: mac m1/x86 build err
_update v1: add x86 err point 123_
_update v2: add x86 err 3 workround_
_update v3: unsolved@add x86 and m1 err(m1 also contain some warning)_ 

# below is mac m1 err
## 1. curl need upgrade, and after upgrade, work.

<details>
  <summary>Click me</summary>
  
```
 % ninja
[0/2] Re-checking globbed directories...
[3946/9265] Building C object contrib/curl-cmake/CMakeFiles/_curl.dir/__/curl/lib/hostip.c.o
FAILED: contrib/curl-cmake/CMakeFiles/_curl.dir/__/curl/lib/hostip.c.o 
/opt/homebrew/bin/ccache /opt/homebrew/opt/llvm/bin/clang -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -DHAS_RESERVED_IDENTIFIER -DHAVE_CONFIG_H -DOS=\"Darwin\" -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Dlibcurl_EXPORTS -isystem /Users/ec2-user/proton/contrib/curl/include -isystem /Users/ec2-user/proton/contrib/curl/lib -isystem /Users/ec2-user/proton/contrib/curl-cmake/. -isystem /Users/ec2-user/proton/contrib/llvm-project/libcxxabi/include -isystem /Users/ec2-user/proton/contrib/boringssl/include -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion  -gdwarf-aranges -pipe -march=armv8-a+crc -fasynchronous-unwind-tables -ffile-prefix-map=/Users/ec2-user/proton=. -falign-functions=32  -Wall -Wno-unused-command-line-argument  -fdiagnostics-absolute-paths -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -std=gnu11 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.15   -D OS_DARWIN -Werror -MD -MT contrib/curl-cmake/CMakeFiles/_curl.dir/__/curl/lib/hostip.c.o -MF contrib/curl-cmake/CMakeFiles/_curl.dir/__/curl/lib/hostip.c.o.d -o contrib/curl-cmake/CMakeFiles/_curl.dir/__/curl/lib/hostip.c.o -c /Users/ec2-user/proton/contrib/curl/lib/hostip.c
/Users/ec2-user/proton/contrib/curl/lib/hostip.c:539:6: error: conflicting types for 'Curl_ipv6works'
bool Curl_ipv6works(struct Curl_easy *data)
     ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.h:104:6: note: previous declaration is here
bool Curl_ipv6works(struct Curl_easy *data);
     ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.c:569:6: error: conflicting types for 'Curl_host_is_ipnum'
bool Curl_host_is_ipnum(const char *hostname)
     ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.h:74:6: note: previous declaration is here
bool Curl_host_is_ipnum(const char *hostname);
     ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.c:601:16: error: conflicting types for 'Curl_resolv'
enum resolve_t Curl_resolv(struct Curl_easy *data,
               ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.h:90:16: note: previous declaration is here
enum resolve_t Curl_resolv(struct Curl_easy *data,
               ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.c:1256:10: error: conflicting types for 'Curl_once_resolved'
CURLcode Curl_once_resolved(struct Curl_easy *data, bool *protocol_done)
         ^
/Users/ec2-user/proton/contrib/curl/lib/hostip.h:144:10: note: previous declaration is here
CURLcode Curl_once_resolved(struct Curl_easy *data, bool *protocol_connect);
         ^
4 errors generated.
[3955/9265] Building CXX object contrib/simdjson-cmake/CMakeFiles/_simdjson.dir/__/simdjson/src/simdjson.cpp.o
ninja: build stopped: subcommand failed.

```
</details>

## 2. azure sdk need modify random val generator, after modify to `#include<random>` instead stdlib random api, works.

<details>
  <summary>Click me</summary>
  
```
% ninja
[0/2] Re-checking globbed directories...
[4105/9267] Building CXX object contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/core/azure-core/src/http/retry_policy.cpp.o
FAILED: contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/core/azure-core/src/http/retry_policy.cpp.o 
/opt/homebrew/bin/ccache /opt/homebrew/opt/llvm/bin/clang++ -DBUILD_CURL_HTTP_TRANSPORT_ADAPTER -DHAS_RESERVED_IDENTIFIER -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/Users/ec2-user/proton/contrib/libxml2/include -I/Users/ec2-user/proton/contrib/libxml2-cmake/linux_x86_64/include -isystem /Users/ec2-user/proton/contrib/azure/sdk/core/azure-core/inc -isystem /Users/ec2-user/proton/contrib/azure/sdk/identity/azure-identity/inc -isystem /Users/ec2-user/proton/contrib/azure/sdk/storage/azure-storage-common/inc -isystem /Users/ec2-user/proton/contrib/azure/sdk/storage/azure-storage-blobs/inc -isystem /Users/ec2-user/proton/contrib/llvm-project/libcxx/include -isystem /Users/ec2-user/proton/contrib/llvm-project/libcxxabi/include -isystem /Users/ec2-user/proton/contrib/boringssl/include -isystem /Users/ec2-user/proton/contrib/curl/include -isystem /Users/ec2-user/proton/contrib/curl/lib -isystem /Users/ec2-user/proton/contrib/curl-cmake/. -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -march=armv8-a+crc -fasynchronous-unwind-tables -ffile-prefix-map=/Users/ec2-user/proton=. -falign-functions=32   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -std=gnu++2b -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.15   -D OS_DARWIN -Werror -nostdinc++ -MD -MT contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/core/azure-core/src/http/retry_policy.cpp.o -MF contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/core/azure-core/src/http/retry_policy.cpp.o.d -o contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/core/azure-core/src/http/retry_policy.cpp.o -c /Users/ec2-user/proton/contrib/azure/sdk/core/azure-core/src/http/retry_policy.cpp
/Users/ec2-user/proton/contrib/azure/sdk/core/azure-core/src/http/retry_policy.cpp:65:12: error: unknown type name 'drand48_data'
    static drand48_data buf;
           ^
1 error generated.
[4114/9267] Building CXX object contrib/azure-cmake/CMakeFiles/_azure_sdk.dir/__/azure/sdk/core/azure-core/src/exception.cpp.o
ninja: build stopped: subcommand failed.

```

</details>

## 3. v8 build error

<details>
  <summary>Click me</summary>
  
```
cmake --build .
[0/2] Re-checking globbed directories...
[1177/5155] Building CXX object contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/trap-handler/handler-inside-posix.cc.o
FAILED: contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/trap-handler/handler-inside-posix.cc.o 
/opt/homebrew/bin/ccache /opt/homebrew/opt/llvm/bin/clang++ -DHAS_RESERVED_IDENTIFIER -DV8_CONCURRENT_MARKING -DV8_HAVE_TARGET_OS -DV8_TARGET_ARCH_ARM64 -DV8_TARGET_OS_MACOS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/Users/ec2-user/proton/contrib/v8-cmake/generated -I/Users/ec2-user/proton/contrib/v8-cmake/v8/include -I/Users/ec2-user/proton/contrib/v8-cmake/v8 -I/Users/ec2-user/proton/contrib/v8-cmake/v8/third_party/zlib -I/Users/ec2-user/proton/build/contrib/v8-cmake -isystem /Users/ec2-user/proton/contrib/llvm-project/libcxx/include -isystem /Users/ec2-user/proton/contrib/llvm-project/libcxxabi/include -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -march=armv8-a+crc -fasynchronous-unwind-tables -ffile-prefix-map=/Users/ec2-user/proton=. -falign-functions=32   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -std=gnu++2b -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.15   -D OS_DARWIN -DV8_ENABLE_WEBASSEMBLY -DV8_ADVANCED_BIGINT_ALGORITHMS -fno-exceptions -Wno-undef -Wno-unused-parameter -Wno-covered-switch-default -Wno-poison-system-directories -Wno-gnu-statement-expression -Wno-comma -Wno-format-nonliteral -Wno-format-pedantic -Wno-missing-noreturn -Wno-conditional-uninitialized -Wno-extra-semi-stmt -Wno-non-virtual-dtor -Wno-shadow-field-in-constructor -Wno-documentation -Wno-reserved-identifier -Wno-newline-eof -Wno-undefined-reinterpret-cast -Wno-error -Wno-implicit-fallthrough -Wno-unused-function -Wno-sign-compare -Wno-deprecated-declarations -Wno-deprecated-pragma -Wno-redundant-parens -Wno-deprecated-anon-enum-enum-conversion -Wno-zero-as-null-pointer-constant -Wno-suggest-override -Wno-dtor-name -Wno-suggest-destructor-override -Wno-inconsistent-missing-destructor-override -Wno-frame-larger-than -Wno-unused-macros -Wno-deprecated-volatile -Wno-cast-function-type -Wno-deprecated-copy-with-dtor -Wno-deprecated-this-capture -Wno-unused-member-function -Wno-shadow -Wno-gnu-anonymous-struct -Wno-shadow-field -Wno-cast-qual -Wno-used-but-marked-unused -Wno-gnu-zero-variadic-macro-arguments -Wno-ambiguous-reversed-operator -Wno-deprecated-copy-with-user-provided-dtor -Wno-shadow-uncaptured-local -Wno-duplicate-enum -Wno-old-style-cast -Werror -nostdinc++ -MD -MT contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/trap-handler/handler-inside-posix.cc.o -MF contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/trap-handler/handler-inside-posix.cc.o.d -o contrib/v8-cmake/CMakeFiles/v8_base_without_compiler.dir/v8/src/trap-handler/handler-inside-posix.cc.o -c /Users/ec2-user/proton/contrib/v8-cmake/v8/src/trap-handler/handler-inside-posix.cc
/Users/ec2-user/proton/contrib/v8-cmake/v8/src/trap-handler/handler-inside-posix.cc:128:40: error: member reference type 'struct __darwin_mcontext64 *' is a pointer; did you mean to use '->'?
    auto* context_ip = &uc->uc_mcontext.pc;
                        ~~~~~~~~~~~~~~~^
                                       ->
/Users/ec2-user/proton/contrib/v8-cmake/v8/src/trap-handler/handler-inside-posix.cc:128:41: error: no member named 'pc' in '__darwin_mcontext64'
    auto* context_ip = &uc->uc_mcontext.pc;
                        ~~~~~~~~~~~~~~~ ^
2 errors generated.
[1186/5155] Building CXX object base/poco/Data/CMakeFiles/_poco_data.dir/src/StatementImpl.cpp.o
ninja: build stopped: subcommand failed.
```

</details>

## 4. err not find symbol

<details>
  <summary> Click me </summary>

```
[2426/2434] Linking CXX executable programs/proton
FAILED: programs/proton 
: && /opt/homebrew/opt/llvm/bin/clang++ -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -march=armv8-a+crc -fasynchronous-unwind-tables -ffile-prefix-map=/Users/ec2-user/proton=. -falign-functions=32   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-shorten-64-to-32 -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -rdynamic -Wl,-U,_inside_main    -u_zone_register src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o programs/CMakeFiles/proton.dir/main.cpp.o -o programs/proton  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./CRC.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./CastOverloadResolver.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./DateOrDateTimeFunctionsConvertion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./DateTimeTransforms.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionChar.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionFQDN.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionFactory.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionFile.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionHashID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionHelpers.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionJoinGet.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionSQLJSON.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionUniqueRandom.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsAES.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsBinaryRepresentation.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsBitToArray.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsBitmap.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsCharsetClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsCodingIP.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsCodingUUID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsConversion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsDecimalArithmetics.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsEmbeddedDictionaries.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsExternalDictionaries.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsHashing.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsJSON.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsLanguageClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsLogical.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsProgrammingClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsRandom.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsRound.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsStringArray.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsStringHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsStringSimilarity.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsTonalityClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./GeoHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./IFunction.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./SubtractSubSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./UTCTimestamp.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./abs.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./acos.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./acosh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addDays.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addHours.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addMonths.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addQuarters.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addSubSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addWeeks.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addYears.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addressToLine.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addressToLineWithInlines.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addressToSymbol.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./aes_decrypt_mysql.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./aes_encrypt_mysql.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./appendTrailingCharIfAbsent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ascii.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./asin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./asinh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./assumeNotNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./atan.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./atan2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./atanh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bar.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base58Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base58Encode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base64Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base64Encode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitAnd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitBoolMaskAnd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitBoolMaskOr.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitCount.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitHammingDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitNot.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitOr.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitRotateLeft.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitRotateRight.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitShiftLeft.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitShiftRight.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitSlice.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitSwapLastTwo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitTest.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitTestAll.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitTestAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitWrapperFunc.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitXor.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./blockNumber.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./blockSerializedSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./blockSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./byteSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./canonicalRand.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./caseWithExpression.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./castOrDefault.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./cbrt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./checkHyperscanRegexp.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./coalesce.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./concat.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./connectionId.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./convertCharset.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./cos.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./cosh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countDigits.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countMatches.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countSubstrings.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countSubstringsCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countSubstringsCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentDatabase.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentProfiles.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentRoles.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentUser.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dateDiff.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dateDiffWithin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dateName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./date_trunc.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./decodeXMLComponent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./decrypt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./defaultValueOfArgumentType.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./defaultValueOfTypeName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./degrees.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./demange.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./divide.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dumpColumnStructure.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./emitVersion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./empty.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./encodeXMLComponent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./encrypt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./endsWith.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./equals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./erf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./erfc.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./errorCodeToName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./evalMLMethod.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./exp.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./exp10.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./exp2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extract.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractAllGroupsHorizontal.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractAllGroupsVertical.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractGroups.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractTextFromHTML.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractTimeZoneFromFunctionArguments.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./factorial.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./filesystem.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./finalizeAggregation.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./flattenTuple.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatDateTime.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableDecimalSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableQuantity.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableTimeDelta.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatRow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromModifiedJulianDay.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromUnixTimestamp64Micro.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromUnixTimestamp64Milli.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromUnixTimestamp64Nano.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fuzzBits.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./gcd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./generateUUIDv4.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geoToH3.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geoToS2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geohashDecode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geohashEncode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geohashesInBox.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getFuzzerData.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getMacro.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getScalar.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getServerPort.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getSetting.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getSizeOfEnumType.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getTypeSerializationStreams.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./globalVariable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greatCircleDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greater.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greaterOrEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greatest.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3CellAreaM2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3CellAreaRads2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3Distance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3EdgeAngle.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3EdgeLengthKm.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3EdgeLengthM.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ExactEdgeLengthKm.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ExactEdgeLengthM.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ExactEdgeLengthRads.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetBaseCell.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetDestinationIndexFromUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetFaces.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetIndexesFromUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetOriginIndexFromUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetPentagonIndexes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetRes0Indexes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetResolution.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetUnidirectionalEdgeBoundary.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetUnidirectionalEdgesFromHexagon.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3HexAreaKm2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3HexAreaM2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3HexRing.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IndexesAreNeighbors.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IsPentagon.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IsResClassIII.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IsValid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3Line.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3NumHexagons.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3PointDist.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToCenterChild.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToChildren.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToGeoBoundary.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToParent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3UnidirectionalEdgeIsValid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3kRing.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3toGeo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasColumnInTable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasThreadFuzzer.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasToken.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasTokenCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hyperscanRegexpChecker.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hypot.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./identity.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./if.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ifNotFinite.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ifNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ignore.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ilike.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./in.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./indexHint.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./initialQueryID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./initializeAggregation.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intDiv.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intDivOrZero.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intExp10.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intExp2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isConstant.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isDecimalOverflow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isFinite.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isIPAddressContainedIn.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isInfinite.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNaN.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNotNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNullable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isValidUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isZeroOrNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./jumpConsistentHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./kostikConsistentHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lcm.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./least.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./left.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lemmatize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lengthUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./less.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lessOrEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lgamma.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./like.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log10.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log1p.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./logTrace.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lowCardinalityIndices.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lowCardinalityKeys.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lower.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lowerUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./makeDate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./map.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mapFilter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./match.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./materialize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mathConstants.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./max2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./meiliMatch.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./min2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./minSampleSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./minus.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./modulo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./moduloOrZero.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./monthName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mortonDecode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mortonEncode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiFuzzyMatchAllIndices.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiFuzzyMatchAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiFuzzyMatchAnyIndex.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiIf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiMatchAllIndices.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiMatchAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiMatchAnyIndex.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositions.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositionsCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositionsCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositionsUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAnyCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAnyCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAnyUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndex.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndexCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndexCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndexUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPosition.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPositionCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPositionCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPositionUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiply.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./negate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./neighbor.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./normalizeQuery.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./normalizeString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./normalizedQueryHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notEmpty.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notILike.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notLike.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./now.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./now64.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./nowInBlock.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./nullIf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./padString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./parseTimeDelta.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./partitionId.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./plus.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./pointInEllipses.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./pointInPolygon.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonArea.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonConvexHull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonPerimeter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsIntersection.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsSymDifference.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsUnion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsWithin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./position.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./positionCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./positionCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./positionUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./pow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./queryID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./radians.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rand.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rand64.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randConstant.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randDistribution.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomFixedString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomPrintableASCII.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomStringUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./readWkt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./regexpQuoteMeta.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./registerFunctions.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./reinterpretAs.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./repeat.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceAll.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceOne.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceRegexpAll.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceRegexpOne.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replicate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./reverse.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./reverseUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./right.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./roundAge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./roundDuration.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./roundToExp2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rowNumberInAllBlocks.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rowNumberInBlock.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningAccumulate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningConcurrency.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningDifference.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningDifferenceStartingWithFirstValue.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2CapContains.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2CapUnion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2CellsIntersect.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2GetNeighbors.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectAdd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectContains.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectIntersection.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectUnion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2ToGeo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./serverConstants.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sigmoid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sign.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sinh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sleep.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sleepEachRow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./snowflake.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sqrt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./startsWith.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./stem.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./stringCutToZero.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./stringToH3.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./substring.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractDays.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractHours.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractMonths.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractQuarters.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractWeeks.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractYears.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./svg.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./synonyms.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tan.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tanh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tgamma.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./throwIf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timeSlot.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timeSlots.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timezoneOf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timezoneOffset.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toBool.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toColumnTypeName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toConcreteType.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toCustomWeek.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toDayOfMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toDayOfWeek.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toDayOfYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toFixedString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toHour.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toISOWeek.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toISOYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toJSONString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toLastDayOfMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toLowCardinality.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toMinute.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toModifiedJulianDay.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toMonday.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toNullable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toQuarter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeDayNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeHourNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeMinuteNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeMonthNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeQuarterNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeSecondNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeWeekNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeYearNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toSecond.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfDay.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfFifteenMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfFiveMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfHour.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfISOYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfInterval.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfMinute.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfQuarter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfSecond.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfSubsecond.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfTenMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toTime.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toTimezone.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toTypeName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toUnixTimestamp64Micro.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toUnixTimestamp64Milli.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toUnixTimestamp64Nano.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toValidUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYYYYMM.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYYYYMMDD.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYYYYMMDDhhmmss.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./today.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tokenExtractors.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./transform.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./translate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./trap.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./trim.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tryBase58Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tryBase64Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tryDecrypt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tuple.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tupleElement.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tupleHammingDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tupleToNameValuePairs.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./upper.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./upperUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./validateNestedArraySizes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./vectorFunctions.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visibleWidth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractBool.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractFloat.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractInt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractRaw.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractUInt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamHas.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./wkt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./yesterday.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ztest.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./array.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayAUC.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayAggregation.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayAll.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCompact.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayConcat.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCount.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCumSum.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCumSumNonNegative.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayDifference.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayDistance.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayDistinct.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayElement.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerate.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateDense.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateDenseRanked.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateRanked.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateUniq.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateUniqRanked.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayExists.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFill.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFilter.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFirstLast.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFirstLastIndex.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFlatten.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayIntersect.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayJoin.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayMap.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayNorm.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPopBack.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPopFront.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPushBack.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPushFront.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayReduce.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayReduceInRanges.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayResize.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayReverse.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arraySlice.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arraySort.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arraySplit.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayUniq.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayWithConstant.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayZip.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./countEqual.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./emptyArray.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./emptyArrayToSingle.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./has.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./hasAll.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./hasAny.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./hasSubstr.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./indexOf.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./length.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./mapOp.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./mapPopulateSeries.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./range.cpp.o  src/Functions/UniqTheta/CMakeFiles/clickhouse_functions_uniqtheta.dir/./FunctionsUniqTheta.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./StreamingNeighbor.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./StreamingNow.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./StreamingNow64.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./earliestTimestamp.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./grok.cpp.o  src/libclickhouse_new_delete.a  src/libclickhouse_common_io.a  src/Common/StringUtils/libstring_utils.a  programs/server/libclickhouse-server-lib.a  programs/client/libclickhouse-client-lib.a  programs/local/libclickhouse-local-lib.a  programs/benchmark/libclickhouse-benchmark-lib.a  programs/format/libclickhouse-format-lib.a  programs/keeper/libclickhouse-keeper-lib.a  programs/git-import/libclickhouse-git-import-lib.a  programs/install/libclickhouse-install-lib.a  programs/klog/libclickhouse-klog-benchmark-lib.a  programs/server/libclickhouse-server-lib.a  -Wl,-force_load /Users/ec2-user/proton/build/programs/server/libclickhouse_server_configs.a -Wl,-undefined,error  programs/client/libclickhouse-client-lib.a  src/AggregateFunctions/libclickhouse_aggregate_functions.a  contrib/libfarmhash/lib_farmhash.a  src/Dictionaries/libclickhouse_dictionaries.a  base/poco/Data/lib_poco_data.a  contrib/libmetrohash/lib_metrohash.a  contrib/murmurhash/lib_murmurhash.a  contrib/hashidsxx-cmake/lib_hashidsxx.a  src/Functions/divide/libdivide_impl.a  src/Functions/divide/libdivide_impl_generic.a  contrib/xxHash-cmake/libxxHash.a  contrib/base64-cmake/lib_base64.a  contrib/cld2-cmake/lib_cld2.a  contrib/h3-cmake/lib_h3.a  src/Functions/GatherUtils/libclickhouse_functions_gatherutils.a  src/Functions/JSONPath/libclickhouse_functions_jsonpath.a  src/TableFunctions/libclickhouse_table_functions.a  src/Storages/System/libclickhouse_storages_system.a  -Wl,-force_load /Users/ec2-user/proton/build/src/Storages/System/libinformation_schema_metadata.a -Wl,-undefined,error  src/Daemon/libdaemon.a  src/Loggers/libloggers.a  base/readpassphrase/libreadpassphrase.a  src/libdbms.a  src/Common/Config/libclickhouse_common_config.a  contrib/yaml-cpp-cmake/lib_yaml_cpp.a  src/Common/ZooKeeper/libclickhouse_common_zookeeper.a  src/Parsers/libclickhouse_parsers.a  src/Access/Common/libclickhouse_common_access.a  contrib/azure-cmake/lib_azure_sdk.a  contrib/curl-cmake/lib_curl.a  contrib/libxml2-cmake/lib_libxml2.a  src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a  contrib/consistent-hashing/lib_consistent_hashing.a  contrib/simdjson-cmake/lib_simdjson.a  src/Storages/ExternalStream/libexternal_stream.a  src/KafkaLog/libklog.a  src/NativeLog/libnlog.a  src/Checkpoint/libcheckpoint.a  contrib/croaring-cmake/lib_roaring.a  contrib/librdkafka-cmake/lib_rdkafka.a  contrib/cyrus-sasl-cmake/lib_sasl2.a  contrib/krb5-cmake/lib_krb5.a  contrib/nuraft-cmake/lib_nuraft.a  contrib/boost-cmake/lib_boost_coroutine.a  src/V8/libV8.a  src/libclickhouse_common_io.a  src/Common/StringUtils/libstring_utils.a  contrib/jemalloc-cmake/lib_jemalloc.a  contrib/muduo-cmake/net/lib_muduo_net.a  contrib/muduo-cmake/base/lib_muduo_base.a  base/widechar_width/libwidechar_width.a  base/base/libcommon.a  base/poco/NetSSL_OpenSSL/lib_poco_net_ssl.a  base/poco/Net/lib_poco_net.a  base/poco/Crypto/lib_poco_crypto.a  base/poco/Util/lib_poco_util.a  base/poco/XML/lib_poco_xml.a  base/poco/XML/lib_poco_xml_expat.a  base/poco/JSON/lib_poco_json.a  base/poco/JSON/lib_poco_json_pdjson.a  contrib/replxx-cmake/lib_replxx.a  contrib/cctz-cmake/lib_cctz.a  -Wl,-force_load /Users/ec2-user/proton/build/contrib/cctz-cmake/libtzdata.a -Wl,-undefined,error  contrib/fmtlib-cmake/lib_fmt.a  contrib/dragonbox-cmake/lib_dragonbox_to_chars.a  contrib/re2-cmake/libre2_st.a  contrib/boost-cmake/lib_boost_program_options.a  contrib/boost-cmake/lib_boost_system.a  contrib/cityhash102/lib_cityhash.a  base/poco/Foundation/lib_poco_foundation.a  base/poco/Foundation/lib_poco_foundation_pcre.a  contrib/xz-cmake/lib_liblzma.a  contrib/aws-cmake/lib_aws.a  contrib/bzip2-cmake/lib_bzip2.a  contrib/v8-cmake/libv8_compiler.a  contrib/v8-cmake/libv8_base_without_compiler.a  contrib/v8-cmake/libv8_snapshot.a  contrib/v8-cmake/libv8_inspector.a  contrib/v8-cmake/libv8_libplatform.a  contrib/v8-cmake/libv8_libsampler.a  contrib/v8-cmake/libv8_libbase.a  contrib/v8-cmake/libv8_initializers.a  contrib/v8-cmake/libv8_torque_generated.a  contrib/v8-cmake/libv8-bytecodes-builtin-list.a  contrib/capnproto-cmake/lib_capnpc.a  contrib/capnproto-cmake/lib_capnp.a  contrib/capnproto-cmake/lib_kj.a  contrib/arrow-cmake/lib_parquet.a  contrib/arrow-cmake/lib_arrow.a  contrib/double-conversion-cmake/lib_double-conversion.a  contrib/brotli-cmake/lib_brotli.a  contrib/boost-cmake/lib_boost_filesystem.a  contrib/flatbuffers/libflatbuffers.a  contrib/arrow-cmake/lib_orc.a  contrib/thrift-cmake/lib_thrift.a  contrib/avro-cmake/lib_avrocpp.a  contrib/boost-cmake/lib_boost_iostreams.a  contrib/openldap-cmake/lib_ldap_r.a  contrib/openldap-cmake/lib_lber.a  src/Server/grpc_protos/libclickhouse_grpc_protos.a  contrib/grpc/libgrpc++.a  contrib/protobuf-cmake/lib_libprotobuf.a  contrib/grpc/libgrpc.a  contrib/re2-cmake/libre2.a  contrib/c-ares/lib/libcares.a  -lresolv  contrib/abseil-cpp/absl/status/libabsl_status.a  -framework CoreFoundation  contrib/grpc/libaddress_sorting.a  contrib/grpc/libupb.a  contrib/grpc/libgpr.a  contrib/s2geometry-cmake/lib_s2.a  contrib/abseil-cpp/absl/container/libabsl_raw_hash_set.a  contrib/abseil-cpp/absl/container/libabsl_hashtablez_sampler.a  contrib/abseil-cpp/absl/strings/libabsl_cord.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_info.a  contrib/abseil-cpp/absl/strings/libabsl_cord_internal.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_functions.a  contrib/abseil-cpp/absl/profiling/libabsl_exponential_biased.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_handle.a  contrib/abseil-cpp/absl/synchronization/libabsl_synchronization.a  contrib/abseil-cpp/absl/debugging/libabsl_symbolize.a  contrib/abseil-cpp/absl/debugging/libabsl_demangle_internal.a  contrib/abseil-cpp/absl/synchronization/libabsl_graphcycles_internal.a  contrib/abseil-cpp/absl/time/libabsl_time.a  contrib/abseil-cpp/absl/time/libabsl_civil_time.a  contrib/abseil-cpp/absl/time/libabsl_time_zone.a  -Xlinker -framework -Xlinker CoreFoundation  contrib/abseil-cpp/absl/base/libabsl_malloc_internal.a  contrib/abseil-cpp/absl/debugging/libabsl_stacktrace.a  contrib/abseil-cpp/absl/debugging/libabsl_debugging_internal.a  contrib/abseil-cpp/absl/hash/libabsl_hash.a  contrib/abseil-cpp/absl/hash/libabsl_city.a  contrib/abseil-cpp/absl/types/libabsl_bad_optional_access.a  contrib/abseil-cpp/absl/types/libabsl_bad_variant_access.a  contrib/abseil-cpp/absl/hash/libabsl_low_level_hash.a  contrib/abseil-cpp/absl/strings/libabsl_str_format_internal.a  contrib/abseil-cpp/absl/strings/libabsl_strings.a  contrib/abseil-cpp/absl/numeric/libabsl_int128.a  contrib/abseil-cpp/absl/base/libabsl_throw_delegate.a  contrib/abseil-cpp/absl/strings/libabsl_strings_internal.a  contrib/abseil-cpp/absl/base/libabsl_base.a  contrib/abseil-cpp/absl/base/libabsl_spinlock_wait.a  contrib/abseil-cpp/absl/base/libabsl_raw_logging_internal.a  contrib/abseil-cpp/absl/base/libabsl_log_severity.a  contrib/rocksdb-cmake/lib_rocksdb.a  contrib/zlib-ng-cmake/lib_zlib.a  contrib/zstd-cmake/lib_zstd.a  contrib/snappy-cmake/lib_snappy.a  contrib/lz4-cmake/lib_lz4.a  contrib/libpqxx-cmake/lib_libpqxx.a  contrib/libpq-cmake/lib_libpq.a  contrib/boringssl-cmake/lib_ssl.a  contrib/boringssl-cmake/lib_crypto.a  -lpthread  contrib/boost-cmake/lib_boost_context.a  contrib/libstemmer-c-cmake/lib_stemmer.a  contrib/wordnet-blast-cmake/lib_wnb.a  contrib/boost-cmake/lib_boost_graph.a  contrib/boost-cmake/lib_boost_regex.a  contrib/lemmagen-c-cmake/lib_lemmagen.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  -Wl,-force_load /Users/ec2-user/proton/build/contrib/nlp-data-cmake/libnlp_dictionaries.a -Wl,-undefined,error  -nodefaultlibs  -lc -lm -lpthread -ldl && cd /Users/ec2-user/proton/build/programs && mkdir -p /Users/ec2-user/proton/build/programs//lib/debug && touch /Users/ec2-user/proton/build/programs//lib/debug/proton.debug
Undefined symbols for architecture arm64:
  "_Curl_macos_init", referenced from:
      _curl_global_init in lib_curl.a(easy.c.o)
      _curl_global_init_mem in lib_curl.a(easy.c.o)
      _curl_easy_init in lib_curl.a(easy.c.o)
  "_iconv", referenced from:
      _xmlCharEncFirstLineInt in lib_libxml2.a(encoding.c.o)
      _xmlCharEncFirstLineInput in lib_libxml2.a(encoding.c.o)
      _xmlCharEncInput in lib_libxml2.a(encoding.c.o)
      _xmlCharEncInFunc in lib_libxml2.a(encoding.c.o)
      _xmlEncOutputChunk in lib_libxml2.a(encoding.c.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in lib_libxml2.a(encoding.c.o)
      _xmlCharEncCloseFunc in lib_libxml2.a(encoding.c.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in lib_libxml2.a(encoding.c.o)
ld: symbol(s) not found for architecture arm64

```

</details>

## 5. build warning trash code for utils/wal-dump can be remove?
[linking_warning.txt](https://github.com/timeplus-io/proton/files/12608321/linking_warning.txt)

# below is mac x86 err

## 3. deprecated in `utils/db-generator/query_db_generator`

tmp workround: https://github.com/ClickHouse/ClickHouse/commit/5be30b9cb73ca47d7621b686ee8dddc483bc99d7
in future? remove trash: https://github.com/ClickHouse/ClickHouse/commit/8860550e87222c09832ce73f70fb5616f8822113

<details>
  <summary>Click me</summary>

```
/Users/ec2-user/proton/utils/db-generator/query_db_generator.cpp:62:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    sprintf(answer, "'%04u-%02u-%02u'", year, month, day);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
/Users/ec2-user/proton/utils/db-generator/query_db_generator.cpp:75:5: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
    sprintf(
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
2 errors generated.
[1522/3971] Building CXX object utils/wal-dump/CMakeFiles/wal-dump.dir/main.cpp.o
ninja: build stopped: subcommand failed.

```
</details>

## 4. err symbol not find same as above.

<details>
  <summary> click me </summary>

```
[2091/2099] Linking CXX executable programs/proton
FAILED: programs/proton 
: && /usr/local/opt/llvm/bin/clang++ -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/Users/ec2-user/proton=. -falign-functions=32 -mbranches-within-32B-boundaries   -Wall -Wno-unused-command-line-argument  -stdlib=libc++ -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-shorten-64-to-32 -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -mmacosx-version-min=10.15 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -rdynamic -Wl,-U,_inside_main    -u_zone_register src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o programs/CMakeFiles/proton.dir/main.cpp.o -o programs/proton  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./CRC.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./CastOverloadResolver.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./DateOrDateTimeFunctionsConvertion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./DateTimeTransforms.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionChar.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionFQDN.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionFactory.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionFile.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionHashID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionHelpers.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionJoinGet.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionSQLJSON.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionUniqueRandom.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsAES.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsBinaryRepresentation.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsBitToArray.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsBitmap.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsCharsetClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsCodingIP.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsCodingUUID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsConversion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsDecimalArithmetics.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsEmbeddedDictionaries.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsExternalDictionaries.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsHashing.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsJSON.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsLanguageClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsLogical.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsProgrammingClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsRandom.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsRound.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsStringArray.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsStringHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsStringSimilarity.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./FunctionsTonalityClassification.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./GeoHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./IFunction.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./SubtractSubSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./UTCTimestamp.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./abs.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./acos.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./acosh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addDays.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addHours.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addMonths.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addQuarters.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addSubSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addWeeks.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addYears.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addressToLine.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addressToLineWithInlines.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./addressToSymbol.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./aes_decrypt_mysql.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./aes_encrypt_mysql.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./appendTrailingCharIfAbsent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ascii.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./asin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./asinh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./assumeNotNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./atan.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./atan2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./atanh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bar.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base58Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base58Encode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base64Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./base64Encode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitAnd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitBoolMaskAnd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitBoolMaskOr.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitCount.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitHammingDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitNot.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitOr.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitRotateLeft.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitRotateRight.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitShiftLeft.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitShiftRight.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitSlice.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitSwapLastTwo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitTest.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitTestAll.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitTestAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitWrapperFunc.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./bitXor.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./blockNumber.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./blockSerializedSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./blockSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./byteSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./canonicalRand.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./caseWithExpression.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./castOrDefault.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./cbrt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./checkHyperscanRegexp.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./coalesce.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./concat.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./connectionId.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./convertCharset.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./cos.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./cosh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countDigits.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countMatches.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countSubstrings.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countSubstringsCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./countSubstringsCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentDatabase.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentProfiles.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentRoles.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./currentUser.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dateDiff.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dateDiffWithin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dateName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./date_trunc.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./decodeXMLComponent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./decrypt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./defaultValueOfArgumentType.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./defaultValueOfTypeName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./degrees.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./demange.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./divide.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./dumpColumnStructure.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./emitVersion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./empty.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./encodeXMLComponent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./encrypt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./endsWith.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./equals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./erf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./erfc.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./errorCodeToName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./evalMLMethod.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./exp.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./exp10.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./exp2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extract.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractAllGroupsHorizontal.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractAllGroupsVertical.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractGroups.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractTextFromHTML.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./extractTimeZoneFromFunctionArguments.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./factorial.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./filesystem.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./finalizeAggregation.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./flattenTuple.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatDateTime.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableDecimalSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableQuantity.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatReadableTimeDelta.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatRow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./formatString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromModifiedJulianDay.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromUnixTimestamp64Micro.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromUnixTimestamp64Milli.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fromUnixTimestamp64Nano.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./fuzzBits.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./gcd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./generateUUIDv4.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geoToH3.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geoToS2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geohashDecode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geohashEncode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./geohashesInBox.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getFuzzerData.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getMacro.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getScalar.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getServerPort.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getSetting.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getSizeOfEnumType.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./getTypeSerializationStreams.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./globalVariable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greatCircleDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greater.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greaterOrEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./greatest.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3CellAreaM2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3CellAreaRads2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3Distance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3EdgeAngle.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3EdgeLengthKm.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3EdgeLengthM.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ExactEdgeLengthKm.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ExactEdgeLengthM.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ExactEdgeLengthRads.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetBaseCell.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetDestinationIndexFromUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetFaces.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetIndexesFromUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetOriginIndexFromUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetPentagonIndexes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetRes0Indexes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetResolution.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetUnidirectionalEdge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetUnidirectionalEdgeBoundary.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3GetUnidirectionalEdgesFromHexagon.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3HexAreaKm2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3HexAreaM2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3HexRing.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IndexesAreNeighbors.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IsPentagon.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IsResClassIII.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3IsValid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3Line.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3NumHexagons.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3PointDist.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToCenterChild.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToChildren.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToGeoBoundary.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToParent.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3ToString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3UnidirectionalEdgeIsValid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3kRing.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./h3toGeo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasColumnInTable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasThreadFuzzer.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasToken.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hasTokenCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hyperscanRegexpChecker.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./hypot.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./identity.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./if.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ifNotFinite.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ifNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ignore.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ilike.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./in.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./indexHint.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./initialQueryID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./initializeAggregation.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intDiv.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intDivOrZero.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intExp10.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./intExp2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isConstant.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isDecimalOverflow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isFinite.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isIPAddressContainedIn.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isInfinite.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNaN.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNotNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isNullable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isValidUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./isZeroOrNull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./jumpConsistentHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./kostikConsistentHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lcm.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./least.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./left.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lemmatize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lengthUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./less.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lessOrEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lgamma.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./like.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log10.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log1p.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./log2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./logTrace.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lowCardinalityIndices.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lowCardinalityKeys.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lower.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./lowerUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./makeDate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./map.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mapFilter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./match.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./materialize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mathConstants.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./max2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./meiliMatch.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./min2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./minSampleSize.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./minus.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./modulo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./moduloOrZero.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./monthName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mortonDecode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./mortonEncode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiFuzzyMatchAllIndices.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiFuzzyMatchAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiFuzzyMatchAnyIndex.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiIf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiMatchAllIndices.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiMatchAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiMatchAnyIndex.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositions.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositionsCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositionsCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAllPositionsUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAny.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAnyCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAnyCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchAnyUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndex.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndexCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndexCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstIndexUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPosition.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPositionCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPositionCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiSearchFirstPositionUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./multiply.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./negate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./neighbor.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./normalizeQuery.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./normalizeString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./normalizedQueryHash.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notEmpty.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notILike.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./notLike.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./now.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./now64.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./nowInBlock.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./nullIf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./padString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./parseTimeDelta.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./partitionId.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./plus.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./pointInEllipses.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./pointInPolygon.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonArea.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonConvexHull.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonPerimeter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsEquals.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsIntersection.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsSymDifference.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsUnion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./polygonsWithin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./position.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./positionCaseInsensitive.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./positionCaseInsensitiveUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./positionUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./pow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./queryID.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./radians.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rand.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rand64.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randConstant.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randDistribution.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomFixedString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomPrintableASCII.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./randomStringUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./readWkt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./regexpQuoteMeta.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./registerFunctions.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./reinterpretAs.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./repeat.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceAll.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceOne.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceRegexpAll.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replaceRegexpOne.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./replicate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./reverse.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./reverseUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./right.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./roundAge.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./roundDuration.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./roundToExp2.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rowNumberInAllBlocks.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./rowNumberInBlock.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningAccumulate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningConcurrency.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningDifference.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./runningDifferenceStartingWithFirstValue.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2CapContains.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2CapUnion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2CellsIntersect.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2GetNeighbors.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectAdd.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectContains.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectIntersection.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2RectUnion.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./s2ToGeo.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./serverConstants.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sigmoid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sign.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sin.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sinh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sleep.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sleepEachRow.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./snowflake.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./sqrt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./startsWith.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./stem.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./stringCutToZero.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./stringToH3.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./substring.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractDays.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractHours.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractMonths.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractQuarters.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractSeconds.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractWeeks.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./subtractYears.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./svg.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./synonyms.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tan.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tanh.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tgamma.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./throwIf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tid.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timeSlot.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timeSlots.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timezoneOf.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./timezoneOffset.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toBool.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toColumnTypeName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toConcreteType.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toCustomWeek.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toDayOfMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toDayOfWeek.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toDayOfYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toFixedString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toHour.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toISOWeek.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toISOYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toJSONString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toLastDayOfMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toLowCardinality.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toMinute.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toModifiedJulianDay.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toMonday.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toNullable.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toQuarter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeDayNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeHourNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeMinuteNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeMonthNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeQuarterNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeSecondNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeWeekNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toRelativeYearNum.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toSecond.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfDay.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfFifteenMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfFiveMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfHour.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfISOYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfInterval.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfMinute.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfMonth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfQuarter.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfSecond.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfSubsecond.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfTenMinutes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toStartOfYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toTime.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toTimezone.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toTypeName.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toUnixTimestamp64Micro.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toUnixTimestamp64Milli.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toUnixTimestamp64Nano.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toValidUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYYYYMM.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYYYYMMDD.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYYYYMMDDhhmmss.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./toYear.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./today.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tokenExtractors.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./transform.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./translate.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./trap.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./trim.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tryBase58Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tryBase64Decode.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tryDecrypt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tuple.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tupleElement.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tupleHammingDistance.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./tupleToNameValuePairs.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./upper.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./upperUTF8.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./validateNestedArraySizes.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./vectorFunctions.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visibleWidth.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractBool.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractFloat.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractInt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractRaw.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractString.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamExtractUInt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./visitParamHas.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./wkt.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./yesterday.cpp.o  src/Functions/CMakeFiles/clickhouse_functions_obj.dir/./ztest.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./array.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayAUC.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayAggregation.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayAll.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCompact.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayConcat.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCount.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCumSum.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayCumSumNonNegative.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayDifference.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayDistance.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayDistinct.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayElement.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerate.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateDense.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateDenseRanked.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateRanked.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateUniq.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayEnumerateUniqRanked.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayExists.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFill.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFilter.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFirstLast.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFirstLastIndex.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayFlatten.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayIntersect.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayJoin.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayMap.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayNorm.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPopBack.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPopFront.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPushBack.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayPushFront.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayReduce.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayReduceInRanges.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayResize.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayReverse.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arraySlice.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arraySort.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arraySplit.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayUniq.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayWithConstant.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./arrayZip.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./countEqual.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./emptyArray.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./emptyArrayToSingle.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./has.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./hasAll.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./hasAny.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./hasSubstr.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./indexOf.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./length.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./mapOp.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./mapPopulateSeries.cpp.o  src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./range.cpp.o  src/Functions/UniqTheta/CMakeFiles/clickhouse_functions_uniqtheta.dir/./FunctionsUniqTheta.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./StreamingNeighbor.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./StreamingNow.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./StreamingNow64.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./earliestTimestamp.cpp.o  src/Functions/Streaming/CMakeFiles/clickhouse_functions_streaming.dir/./grok.cpp.o  src/libclickhouse_new_delete.a  src/libclickhouse_common_io.a  src/Common/StringUtils/libstring_utils.a  programs/server/libclickhouse-server-lib.a  programs/client/libclickhouse-client-lib.a  programs/local/libclickhouse-local-lib.a  programs/benchmark/libclickhouse-benchmark-lib.a  programs/format/libclickhouse-format-lib.a  programs/keeper/libclickhouse-keeper-lib.a  programs/git-import/libclickhouse-git-import-lib.a  programs/install/libclickhouse-install-lib.a  programs/klog/libclickhouse-klog-benchmark-lib.a  programs/server/libclickhouse-server-lib.a  -Wl,-force_load /Users/ec2-user/proton/build/programs/server/libclickhouse_server_configs.a -Wl,-undefined,error  programs/client/libclickhouse-client-lib.a  src/AggregateFunctions/libclickhouse_aggregate_functions.a  contrib/libfarmhash/lib_farmhash.a  src/Dictionaries/libclickhouse_dictionaries.a  base/poco/Data/lib_poco_data.a  contrib/libmetrohash/lib_metrohash.a  contrib/murmurhash/lib_murmurhash.a  contrib/hashidsxx-cmake/lib_hashidsxx.a  src/Functions/divide/libdivide_impl.a  src/Functions/divide/libdivide_impl_sse2.a  src/Functions/divide/libdivide_impl_avx2.a  contrib/xxHash-cmake/libxxHash.a  contrib/base64-cmake/lib_base64.a  contrib/cld2-cmake/lib_cld2.a  contrib/h3-cmake/lib_h3.a  contrib/vectorscan-cmake/lib_vectorscan.a  src/Functions/GatherUtils/libclickhouse_functions_gatherutils.a  src/Functions/JSONPath/libclickhouse_functions_jsonpath.a  src/TableFunctions/libclickhouse_table_functions.a  src/Storages/System/libclickhouse_storages_system.a  -Wl,-force_load /Users/ec2-user/proton/build/src/Storages/System/libinformation_schema_metadata.a -Wl,-undefined,error  src/Daemon/libdaemon.a  src/Loggers/libloggers.a  base/readpassphrase/libreadpassphrase.a  src/libdbms.a  src/Common/Config/libclickhouse_common_config.a  contrib/yaml-cpp-cmake/lib_yaml_cpp.a  src/Common/ZooKeeper/libclickhouse_common_zookeeper.a  src/Parsers/libclickhouse_parsers.a  src/Access/Common/libclickhouse_common_access.a  contrib/azure-cmake/lib_azure_sdk.a  contrib/curl-cmake/lib_curl.a  contrib/libxml2-cmake/lib_libxml2.a  src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a  contrib/consistent-hashing/lib_consistent_hashing.a  contrib/simdjson-cmake/lib_simdjson.a  src/Storages/ExternalStream/libexternal_stream.a  src/KafkaLog/libklog.a  src/NativeLog/libnlog.a  src/Checkpoint/libcheckpoint.a  contrib/croaring-cmake/lib_roaring.a  contrib/librdkafka-cmake/lib_rdkafka.a  contrib/cyrus-sasl-cmake/lib_sasl2.a  contrib/krb5-cmake/lib_krb5.a  contrib/nuraft-cmake/lib_nuraft.a  contrib/boost-cmake/lib_boost_coroutine.a  src/V8/libV8.a  src/libclickhouse_common_io.a  src/Common/StringUtils/libstring_utils.a  contrib/jemalloc-cmake/lib_jemalloc.a  contrib/muduo-cmake/net/lib_muduo_net.a  contrib/muduo-cmake/base/lib_muduo_base.a  base/widechar_width/libwidechar_width.a  base/base/libcommon.a  base/poco/NetSSL_OpenSSL/lib_poco_net_ssl.a  base/poco/Net/lib_poco_net.a  base/poco/Crypto/lib_poco_crypto.a  base/poco/Util/lib_poco_util.a  base/poco/XML/lib_poco_xml.a  base/poco/XML/lib_poco_xml_expat.a  base/poco/JSON/lib_poco_json.a  base/poco/JSON/lib_poco_json_pdjson.a  contrib/replxx-cmake/lib_replxx.a  contrib/cctz-cmake/lib_cctz.a  -Wl,-force_load /Users/ec2-user/proton/build/contrib/cctz-cmake/libtzdata.a -Wl,-undefined,error  contrib/fmtlib-cmake/lib_fmt.a  contrib/dragonbox-cmake/lib_dragonbox_to_chars.a  contrib/re2-cmake/libre2_st.a  contrib/boost-cmake/lib_boost_program_options.a  contrib/boost-cmake/lib_boost_system.a  contrib/cityhash102/lib_cityhash.a  base/poco/Foundation/lib_poco_foundation.a  base/poco/Foundation/lib_poco_foundation_pcre.a  contrib/libcpuid-cmake/lib_cpuid.a  contrib/xz-cmake/lib_liblzma.a  contrib/aws-cmake/lib_aws.a  contrib/bzip2-cmake/lib_bzip2.a  contrib/v8-cmake/libv8_compiler.a  contrib/v8-cmake/libv8_base_without_compiler.a  contrib/v8-cmake/libv8_snapshot.a  contrib/v8-cmake/libv8_inspector.a  contrib/v8-cmake/libv8_libplatform.a  contrib/v8-cmake/libv8_libsampler.a  contrib/v8-cmake/libv8_libbase.a  contrib/v8-cmake/libv8_initializers.a  contrib/v8-cmake/libv8_torque_generated.a  contrib/v8-cmake/libv8-bytecodes-builtin-list.a  contrib/capnproto-cmake/lib_capnpc.a  contrib/capnproto-cmake/lib_capnp.a  contrib/capnproto-cmake/lib_kj.a  contrib/arrow-cmake/lib_parquet.a  contrib/arrow-cmake/lib_arrow.a  contrib/double-conversion-cmake/lib_double-conversion.a  contrib/brotli-cmake/lib_brotli.a  contrib/boost-cmake/lib_boost_filesystem.a  contrib/flatbuffers/libflatbuffers.a  contrib/arrow-cmake/lib_orc.a  contrib/thrift-cmake/lib_thrift.a  contrib/avro-cmake/lib_avrocpp.a  contrib/boost-cmake/lib_boost_iostreams.a  contrib/openldap-cmake/lib_ldap_r.a  contrib/openldap-cmake/lib_lber.a  src/Server/grpc_protos/libclickhouse_grpc_protos.a  contrib/grpc/libgrpc++.a  contrib/protobuf-cmake/lib_libprotobuf.a  contrib/grpc/libgrpc.a  contrib/re2-cmake/libre2.a  contrib/c-ares/lib/libcares.a  -lresolv  contrib/abseil-cpp/absl/status/libabsl_status.a  -framework CoreFoundation  contrib/grpc/libaddress_sorting.a  contrib/grpc/libupb.a  contrib/grpc/libgpr.a  contrib/s2geometry-cmake/lib_s2.a  contrib/abseil-cpp/absl/container/libabsl_raw_hash_set.a  contrib/abseil-cpp/absl/container/libabsl_hashtablez_sampler.a  contrib/abseil-cpp/absl/strings/libabsl_cord.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_info.a  contrib/abseil-cpp/absl/strings/libabsl_cord_internal.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_functions.a  contrib/abseil-cpp/absl/profiling/libabsl_exponential_biased.a  contrib/abseil-cpp/absl/strings/libabsl_cordz_handle.a  contrib/abseil-cpp/absl/synchronization/libabsl_synchronization.a  contrib/abseil-cpp/absl/debugging/libabsl_symbolize.a  contrib/abseil-cpp/absl/debugging/libabsl_demangle_internal.a  contrib/abseil-cpp/absl/synchronization/libabsl_graphcycles_internal.a  contrib/abseil-cpp/absl/time/libabsl_time.a  contrib/abseil-cpp/absl/time/libabsl_civil_time.a  contrib/abseil-cpp/absl/time/libabsl_time_zone.a  -Xlinker -framework -Xlinker CoreFoundation  contrib/abseil-cpp/absl/base/libabsl_malloc_internal.a  contrib/abseil-cpp/absl/debugging/libabsl_stacktrace.a  contrib/abseil-cpp/absl/debugging/libabsl_debugging_internal.a  contrib/abseil-cpp/absl/hash/libabsl_hash.a  contrib/abseil-cpp/absl/hash/libabsl_city.a  contrib/abseil-cpp/absl/types/libabsl_bad_optional_access.a  contrib/abseil-cpp/absl/types/libabsl_bad_variant_access.a  contrib/abseil-cpp/absl/hash/libabsl_low_level_hash.a  contrib/abseil-cpp/absl/strings/libabsl_str_format_internal.a  contrib/abseil-cpp/absl/strings/libabsl_strings.a  contrib/abseil-cpp/absl/numeric/libabsl_int128.a  contrib/abseil-cpp/absl/base/libabsl_throw_delegate.a  contrib/abseil-cpp/absl/strings/libabsl_strings_internal.a  contrib/abseil-cpp/absl/base/libabsl_base.a  contrib/abseil-cpp/absl/base/libabsl_spinlock_wait.a  contrib/abseil-cpp/absl/base/libabsl_raw_logging_internal.a  contrib/abseil-cpp/absl/base/libabsl_log_severity.a  contrib/rocksdb-cmake/lib_rocksdb.a  contrib/zlib-ng-cmake/lib_zlib.a  contrib/zstd-cmake/lib_zstd.a  contrib/snappy-cmake/lib_snappy.a  contrib/lz4-cmake/lib_lz4.a  contrib/libpqxx-cmake/lib_libpqxx.a  contrib/libpq-cmake/lib_libpq.a  contrib/boringssl-cmake/lib_ssl.a  contrib/boringssl-cmake/lib_crypto.a  -lpthread  contrib/boost-cmake/lib_boost_context.a  contrib/libstemmer-c-cmake/lib_stemmer.a  contrib/wordnet-blast-cmake/lib_wnb.a  contrib/boost-cmake/lib_boost_graph.a  contrib/boost-cmake/lib_boost_regex.a  contrib/lemmagen-c-cmake/lib_lemmagen.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  -Wl,-force_load /Users/ec2-user/proton/build/contrib/nlp-data-cmake/libnlp_dictionaries.a -Wl,-undefined,error  -nodefaultlibs  -lc -lm -lpthread -ldl && cd /Users/ec2-user/proton/build/programs && mkdir -p /Users/ec2-user/proton/build/programs//lib/debug && touch /Users/ec2-user/proton/build/programs//lib/debug/proton.debug
Undefined symbols for architecture x86_64:
  "_Curl_macos_init", referenced from:
      _curl_global_init in lib_curl.a(easy.c.o)
      _curl_global_init_mem in lib_curl.a(easy.c.o)
      _curl_easy_init in lib_curl.a(easy.c.o)
  "_iconv", referenced from:
      _xmlCharEncFirstLineInt in lib_libxml2.a(encoding.c.o)
      _xmlCharEncFirstLineInput in lib_libxml2.a(encoding.c.o)
      _xmlCharEncInput in lib_libxml2.a(encoding.c.o)
      _xmlCharEncInFunc in lib_libxml2.a(encoding.c.o)
      _xmlEncOutputChunk in lib_libxml2.a(encoding.c.o)
  "_iconv_close", referenced from:
      _xmlFindCharEncodingHandler in lib_libxml2.a(encoding.c.o)
      _xmlCharEncCloseFunc in lib_libxml2.a(encoding.c.o)
  "_iconv_open", referenced from:
      _xmlFindCharEncodingHandler in lib_libxml2.a(encoding.c.o)
ld: symbol(s) not found for architecture x86_64
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
ec2-user@ip-172-31-43-140 build % nm -C contrib/libxml2-cmake/lib_libxml2.a| grep iconv
contrib/libxml2-cmake/lib_libxml2.a:SAX.c.o: no symbols
                 U _iconv
                 U _iconv_close
                 U _iconv_open
contrib/libxml2-cmake/lib_libxml2.a:legacy.c.o: no symbols
contrib/libxml2-cmake/lib_libxml2.a:xzlib.c.o: no symbols

```

</details>

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by yokofly**
fix #94

### CODE REVIEW

File: programs/klog/klog.cpp [hunk 1]
```diff
@@ -825,7 +825,7 @@ void consume(KafkaWALPtrs & wals, const BenchmarkSettings & bench_settings)
             // ctx.schemas.push_back(table_schema); ? error: no member named 'schemas' in 'DWAL::KafkaWALContext'
 
             atomic_uint64_t consumed = 0;
-            Int32 batch = 100;
+            uint64_t batch = 100;
```
Comment (yokofly) [inline programs/klog/klog.cpp]:
```
/programs/klog/klog.cpp:837:60: error: comparison of integers of different signs: 'unsigned long' and 'Int32' (aka 'int') [-Werror,-Wsign-compare]
                    auto count = (max_messages - consumed) > batch ? batch : (max_messages - consumed);
                                  ~~~~~~~~~~~~~~~~~~~~~~~  ^ ~~~~~
1 error generated.
```

File: src/AggregateFunctions/AggregateFunctionMinMaxK.cpp [hunk 2]
```diff
@@ -14,6 +14,9 @@
 #include <IO/ReadBufferFromString.h>
 #include <Common/FieldVisitorConvertToNumber.h>
 
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wgnu-zero-variadic-macro-arguments"
```
Comment (yokofly) [inline src/AggregateFunctions/AggregateFunctionMinMaxK.cpp]:
```
src/AggregateFunctions/AggregateFunctionMinMaxK.cpp:73:26: error: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Werror,-Wgnu-zero-variadic-macro-arguments]
                M(UInt8, ##__VA_ARGS__); \
                         ^
```

File: src/Functions/FunctionUniqueRandom.cpp [hunk 3]
```diff
@@ -39,7 +39,7 @@ ColumnPtr generateUniqueIdColumn(size_t rows_num, size_t num_of_uniques)
 {
     auto unique_id_col = ColumnVector<UInt64>::create(rows_num);
     auto & unique_ids = unique_id_col->getData();
-    for (auto idx = 0; idx < rows_num; ++idx)
+    for (size_t idx = 0; idx < rows_num; ++idx)
```
Comment (yokofly) [inline src/Functions/FunctionUniqueRandom.cpp]:
```
/src/Functions/FunctionUniqueRandom.cpp:103:16: note: expanded from macro 'CREATE_DATA_GENERATOR'
        return createDataGenerator<TYPE_INDEX, TYPE>();
               ^
/src/Functions/FunctionUniqueRandom.cpp:67:36: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
            for (auto idx = 0; idx < rows_num; idx++)
                               ~~~ ^ ~~~~~~~~
```

File: src/Interpreters/Aggregator.cpp [hunk 4]
```diff
@@ -1083,8 +1083,8 @@ void NO_INLINE Aggregator::executeImplBatch(
             AggregateDataPtr * places_ptr = places.get();
 
             /// It is ok to re-flush if it is flush already, then we don't need maintain a map to check if it is ready flushed
-            for (size_t i = row_begin; i < row_end; ++i)
-                inst->batch_that->flush(places_ptr[i] + inst->state_offset);
+            for (size_t idx = row_begin; idx < row_end; ++idx)
```
Comment (yokofly) [inline src/Interpreters/Aggregator.cpp]:
```
/src/Interpreters/Aggregator.cpp:1086:25: error: declaration shadows a local variable [-Werror,-Wshadow]
            for (size_t i = row_begin; i < row_end; ++i)
                        ^
/src/Interpreters/Aggregator.cpp:1063:17: note: previous declaration is here
    for (size_t i = 0; i < aggregate_functions.size(); ++i)
```

File: src/Functions/UserDefined/UserDefinedFunctionFactory.cpp [hunk 5]
```diff
@@ -77,7 +77,7 @@ AggregateFunctionPtr UserDefinedFunctionFactory::getAggregateFunction(
                 types.size(),
                 config->name);
 
-        for (int i = 0; i < config->arguments.size(); i++)
+        for (size_t i = 0; i < config->arguments.size(); i++)
```
Comment (yokofly) [inline src/Functions/UserDefined/UserDefinedFunctionFactory.cpp]:
```
/src/Functions/UserDefined/UserDefinedFunctionFactory.cpp:80:27: error: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
        for (int i = 0; i < config->arguments.size(); i++)
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
```

File: src/Functions/UserDefined/UserDefinedFunctionBase.h [hunk 6]
```diff
@@ -26,7 +26,7 @@ class UserDefinedFunctionBase : public IFunction
     {
     }
 
-    virtual ~UserDefinedFunctionBase() = default;
+    virtual ~UserDefinedFunctionBase() override = default;
```
Comment (yokofly) [inline src/Functions/UserDefined/UserDefinedFunctionBase.h]:
```
src/Functions/UserDefined/UserDefinedFunctionBase.h:29:13: error: '~UserDefinedFunctionBase' overrides a destructor but is not marked 'override' [-Werror,-Winconsistent-missing-destructor-override]
    virtual ~UserDefinedFunctionBase() = default;
```

File: src/Interpreters/InterpreterSystemQuery.cpp [hunk 7]
```diff
@@ -147,7 +147,7 @@ AccessType getRequiredAccessType(StorageActionBlockType action_type)
 }
 
 /// proton: starts.
-bool shouldBeDistributed(ASTSystemQuery & system, ContextMutablePtr & ctx)
+[[maybe_unused]] bool shouldBeDistributed(ASTSystemQuery & system, ContextMutablePtr & ctx)
```
Comment (yokofly) [inline src/Interpreters/InterpreterSystemQuery.cpp]:
```
/src/Interpreters/InterpreterSystemQuery.cpp:150:6: error: unused function 'shouldBeDistributed' [-Werror,-Wunused-function]
bool shouldBeDistributed(ASTSystemQuery & system, ContextMutablePtr & ctx)
     ^
```

File: src/Interpreters/Streaming/ConcurrentHashJoin.cpp [hunk 8]
```diff
@@ -494,7 +494,7 @@ void ConcurrentHashJoin::deserialize(ReadBuffer & rb)
 
     Int64 num_shards;
     DB::readVarInt(num_shards, rb);
-    if (num_shards != hash_joins.size())
+    if (num_shards != static_cast<long>(hash_joins.size()))
```
Comment (yokofly) [inline src/Interpreters/Streaming/ConcurrentHashJoin.cpp]:
```
/src/Interpreters/Streaming/ConcurrentHashJoin.cpp:497:20: error: comparison of integers of different signs: 'Int64' (aka 'long') and 'size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
    if (num_shards != hash_joins.size())
        ~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
1 error generated.
```

File: src/Interpreters/Streaming/HashJoin.cpp [hunk 9]
```diff
@@ -743,7 +743,7 @@ size_t insertFromBlockImpl(
     }
 }
 
-inline void addDeltaColumn(Block & block, size_t rows)
+[[maybe_unused]] inline void addDeltaColumn(Block & block, size_t rows)
```
Comment (yokofly) [inline src/Interpreters/Streaming/HashJoin.cpp]:
```
src/Interpreters/Streaming/HashJoin.cpp:746:13: error: unused function 'addDeltaColumn' [-Werror,-Wunused-function]
inline void addDeltaColumn(Block & block, size_t rows)
            ^
1 error generated.‘
```

File: src/Interpreters/Streaming/WindowCommon.cpp [hunk 10]
```diff
@@ -676,15 +676,15 @@ WindowParams::WindowParams(TableFunctionDescriptionPtr window_desc) : desc(std::
     time_col_is_datetime64 = isDateTime64(desc->argument_types[0]);
     if (time_col_is_datetime64)
     {
-        const auto & type = assert_cast<const DataTypeDateTime64 &>(*desc->argument_types[0].get());
-        time_scale = type.getScale();
-        time_zone = &type.getTimeZone();
+        const auto & datetime64_type = assert_cast<const DataTypeDateTime64 &>(*desc->argument_types[0].get());
```
Comment (yokofly) [inline src/Interpreters/Streaming/WindowCommon.cpp]:
```
/src/Interpreters/Streaming/WindowCommon.cpp:679:22: error: declaration shadows a field of 'DB::Streaming::WindowParams' [-Werror,-Wshadow]
        const auto & type = assert_cast<const DataTypeDateTime64 &>(*desc->argument_types[0].get());
                     ^
/src/Interpreters/Streaming/WindowCommon.h:229:16: note: previous declaration is here
    WindowType type;
               ^
/src/Interpreters/Streaming/WindowCommon.cpp:685:22: error: declaration shadows a field of 'DB::Streaming::WindowParams' [-Werror,-Wshadow]
        const auto & type = assert_cast<const DataTypeDateTime &>(*desc->argument_types[0].get());
                     ^
/src/Interpreters/Streaming/WindowCommon.h:229:16: note: previous declaration is here
    WindowType type;
               ^
2 errors generated.
```

File: src/Interpreters/TreeOptimizer.cpp [hunk 11]
```diff
@@ -679,7 +679,7 @@ void optimizeSumIfFunctions(ASTPtr & query)
     RewriteSumIfFunctionVisitor(data).visit(query);
 }
 
-void optimizeCountConstantAndSumOne(ASTPtr & query)
+[[maybe_unused]] void optimizeCountConstantAndSumOne(ASTPtr & query)
```
Comment (yokofly) [inline src/Interpreters/TreeOptimizer.cpp]:
```
/src/Interpreters/TreeOptimizer.cpp:682:6: error: unused function 'optimizeCountConstantAndSumOne' [-Werror,-Wunused-function]
void optimizeCountConstantAndSumOne(ASTPtr & query)
     ^
```

File: src/Processors/Formats/Impl/AvroRowInputFormat.cpp [hunk 12]
```diff
@@ -298,7 +298,7 @@ AvroDeserializer::DeserializeFn AvroDeserializer::createDeserializeFn(avro::Node
                 return [non_null_union_index, nested_deserialize](IColumn & column, avro::Decoder & decoder)
                 {
                     ColumnNullable & col = assert_cast<ColumnNullable &>(column);
-                    int union_index = static_cast<int>(decoder.decodeUnionIndex());
+                    size_t union_index = static_cast<size_t>(decoder.decodeUnionIndex());
```
Comment (yokofly) [inline src/Processors/Formats/Impl/AvroRowInputFormat.cpp]:
```
src/Processors/Formats/Impl/AvroRowInputFormat.cpp:302:37: error: comparison of integers of different signs: 'int' and 'const size_t' (aka 'const unsigned long') [-Werror,-Wsign-compare]
                    if (union_index == non_null_union_index)
                        ~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

File: src/Processors/Formats/Impl/ORCBlockInputFormat.cpp [hunk 13]
```diff
@@ -47,9 +47,11 @@ Chunk ORCBlockInputFormat::generate()
     }
 
     std::shared_ptr<arrow::Table> table;
-    arrow::Status table_status = batch_reader->ReadAll(&table);
-    if (!table_status.ok())
-        throw ParsingException(ErrorCodes::CANNOT_READ_ALL_DATA, "Error while reading batch of ORC data: {}", table_status.ToString());
+    arrow::Result<std::shared_ptr<arrow::Table>> table_result = batch_reader->ToTable();
```
Comment (yokofly) [inline src/Processors/Formats/Impl/ORCBlockInputFormat.cpp]:
```
src/Processors/Formats/Impl/ORCBlockInputFormat.cpp:50:48: error: 'ReadAll' is deprecated: Deprecated in 8.0.0. Use ToTable instead. [-Werror,-Wdeprecated-declarations]
    arrow::Status table_status = batch_reader->ReadAll(&table);
                                               ^
/contrib/arrow/cpp/src/arrow/record_batch.h:321:3: note: 'ReadAll' has been explicitly marked deprecated here
  ARROW_DEPRECATED("Deprecated in 8.0.0. Use ToTable instead.")
  ^
/contrib/arrow/cpp/src/arrow/util/macros.h:93:35: note: expanded from macro 'ARROW_DEPRECATED'
#  define ARROW_DEPRECATED(...) [[deprecated(__VA_ARGS__)]]
                                  ^
1 error generated.
```

File: src/Processors/Transforms/Streaming/ChangelogConvertTransform.h [hunk 14]
```diff
@@ -83,7 +83,7 @@ class ChangelogConvertTransform final : public IProcessor
     /// std::mutex mutex;
 
     SERDE size_t late_rows = 0;
-    SERDE CachedBlockMetrics metrics;
+    SERDE CachedBlockMetrics cached_block_metrics;
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/ChangelogConvertTransform.h]:
```
/src/Processors/Transforms/Streaming/ChangelogConvertTransform.h:86:30: error: non-static data member 'metrics' of 'ChangelogConvertTransform' shadows member inherited from type 'IProcessor' [-Werror,-Wshadow-field]
    SERDE CachedBlockMetrics metrics;
                             ^
/src/Processors/IProcessor.h:386:22: note: declared here
    ProcessorMetrics metrics;
```

File: src/Processors/Transforms/Streaming/HopAggregatingTransform.cpp [hunk 15]
```diff
@@ -30,18 +30,18 @@ HopAggregatingTransform::HopAggregatingTransform(
 {
 }
 
-WindowsWithBuckets HopAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark) const
+WindowsWithBuckets HopAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark_) const
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/HopAggregatingTransform.cpp]:
```
/src/Processors/Transforms/Streaming/HopAggregatingTransform.cpp:33:91: error: parameter 'watermark' shadows member inherited from type 'AggregatingTransform' [-Werror,-Wshadow-field]
WindowsWithBuckets HopAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark) const
                                                                                          ^
/src/Processors/Transforms/Streaming/AggregatingTransform.h:215:19: note: declared here
    SERDE Int64 & watermark;
```

File: src/Processors/Transforms/Streaming/JoinTransform.cpp [hunk 16]
```diff
@@ -148,9 +148,9 @@ void JoinTransform::work()
 
                 if (input_chunk.hasWatermark())
                 {
-                    auto watermark = input_chunk.getChunkContext()->getWatermark();
+                    auto input_chunk_watermark = input_chunk.getChunkContext()->getWatermark();
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/JoinTransform.cpp]:
```
src/Processors/Transforms/Streaming/JoinTransform.cpp:151:26: error: declaration shadows a field of 'DB::Streaming::JoinTransform' [-Werror,-Wshadow]
                    auto watermark = input_chunk.getChunkContext()->getWatermark();
                         ^
/src/Processors/Transforms/Streaming/JoinTransform.h:84:19: note: previous declaration is here
    SERDE int64_t watermark = INVALID_WATERMARK;
                  ^
```

File: src/Processors/Transforms/Streaming/SessionAggregatingTransform.cpp [hunk 17]
```diff
@@ -69,34 +69,34 @@ std::pair<bool, bool> SessionAggregatingTransform::executeOrMergeColumns(Chunk &
     return result;
 }
 
-WindowsWithBuckets SessionAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark) const
+WindowsWithBuckets SessionAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark_) const
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/SessionAggregatingTransform.cpp]:
```
src/Processors/Transforms/Streaming/SessionAggregatingTransform.cpp:72:95: error: parameter 'watermark' shadows member inherited from type 'AggregatingTransform' [-Werror,-Wshadow-field]
WindowsWithBuckets SessionAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark) const
                                                                                              ^
/src/Processors/Transforms/Streaming/AggregatingTransform.h:215:19: note: declared here
    SERDE Int64 & watermark;
```

File: src/Processors/Transforms/Streaming/SessionHelper.cpp [hunk 18]
```diff
@@ -222,9 +222,9 @@ void assignWindow(
     /// Then the window start/end will be rewrited by session_id later
     for (size_t pos = 0; auto & column : columns)
     {
-        if (pos == wstart_col_pos)
+        if (pos == static_cast<size_t>(wstart_col_pos))
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/SessionHelper.cpp]:
```
src/Processors/Transforms/Streaming/SessionHelper.cpp:225:17: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'ssize_t' (aka 'long') [-Werror,-Wsign-compare]
        if (pos == wstart_col_pos)
            ~~~ ^  ~~~~~~~~~~~~~~
```

File: src/Processors/Transforms/Streaming/SessionHelper.cpp [hunk 19]
```diff
@@ -222,9 +222,9 @@ void assignWindow(
...
             column = IColumn::mutate(session_id_array.getDataPtr());
-        else if (pos == wend_col_pos)
+        else if (pos == static_cast<size_t>(wend_col_pos))
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/SessionHelper.cpp]:
```
src/Processors/Transforms/Streaming/SessionHelper.cpp:227:22: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'ssize_t' (aka 'long') [-Werror,-Wsign-compare]
        else if (pos == wend_col_pos)
                 ~~~ ^  ~~~~~~~~~~~~
```

File: src/Processors/Transforms/Streaming/TumbleAggregatingTransform.cpp [hunk 20]
```diff
@@ -29,9 +29,9 @@ TumbleAggregatingTransform::TumbleAggregatingTransform(
 {
 }
 
-WindowsWithBuckets TumbleAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark) const
+WindowsWithBuckets TumbleAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark_) const
```
Comment (yokofly) [inline src/Processors/Transforms/Streaming/TumbleAggregatingTransform.cpp]:
```
src/Processors/Transforms/Streaming/TumbleAggregatingTransform.cpp:32:94: error: parameter 'watermark' shadows member inherited from type 'AggregatingTransform' [-Werror,-Wshadow-field]
WindowsWithBuckets TumbleAggregatingTransform::getLocalFinalizedWindowsWithBucketsImpl(Int64 watermark) const
                                                                                             ^
/src/Processors/Transforms/Streaming/AggregatingTransform.h:215:19: note: declared here
    SERDE Int64 & watermark;
```

File: src/Server/RestRouterHandlers/TableRestRouterHandler.cpp [hunk 21]
```diff
@@ -341,12 +341,12 @@ std::pair<String, Int32> TableRestRouterHandler::executeDelete(const Poco::JSON:
     return {processQuery(query), HTTPResponse::HTTP_OK};
 }
 
-void TableRestRouterHandler::buildRetentionSettings(Poco::JSON::Object & resp_table, const String & database, const String & table) const
+void TableRestRouterHandler::buildRetentionSettings(Poco::JSON::Object & resp_table, const String & database_, const String & table) const
```
Comment (yokofly) [inline src/Server/RestRouterHandlers/TableRestRouterHandler.cpp]:
```
src/Server/RestRouterHandlers/TableRestRouterHandler.cpp:344:101: error: parameter 'database' shadows member inherited from type 'RestRouterHandler' [-Werror,-Wshadow-field]
void TableRestRouterHandler::buildRetentionSettings(Poco::JSON::Object & resp_table, const String & database, const String & table) const
                                                                                                    ^
/src/Server/RestRouterHandlers/RestRouterHandler.h:239:12: note: declared here
    String database;
           ^
1 error generated.
```

File: src/Storages/StorageDictionary.cpp [hunk 22]
```diff
@@ -146,9 +146,9 @@ StorageDictionary::~StorageDictionary()
 }
 
 /// proton: starts. Add views dependencies check
-void StorageDictionary::checkTableCanBeDropped(ContextPtr context) const
+void StorageDictionary::checkTableCanBeDropped(ContextPtr context_) const
```
Comment (yokofly) [inline src/Storages/StorageDictionary.cpp]:
```
src/Storages/StorageDictionary.cpp:165:60: error: parameter 'context' shadows member inherited from type 'WithContextImpl<>' [-Werror,-Wshadow-field]
void StorageDictionary::checkTableCanBeDetached(ContextPtr context) const
                                                           ^
/src/Interpreters/Context_fwd.h:47:10: note: declared here
    Weak context;
         ^
2 errors generated.
```

File: src/Storages/StorageMergeTree.cpp [hunk 23]
```diff
@@ -313,9 +313,9 @@ StorageMergeTree::write(const ASTPtr & /*query*/, const StorageMetadataPtr & met
 }
 
 /// proton: starts. Add views dependencies check
-void StorageMergeTree::checkTableCanBeDropped(ContextPtr context) const
+void StorageMergeTree::checkTableCanBeDropped(ContextPtr context_) const
```
Comment (yokofly) [inline src/Storages/StorageMergeTree.cpp]:
```
src/Storages/StorageMergeTree.cpp:316:58: error: parameter 'context' shadows member inherited from type 'WithContextImpl<std::shared_ptr<DB::Context>>' [-Werror,-Wshadow-field]
void StorageMergeTree::checkTableCanBeDropped(ContextPtr context) const
                                                         ^
/src/Interpreters/Context_fwd.h:47:10: note: declared here
    Weak context;
```

File: src/Storages/Streaming/ProxyStream.cpp [hunk 24]
```diff
@@ -299,10 +299,10 @@ Block ProxyStream::checkAndGetOutputHeader(const Names & required_columns, const
     output_header.reserve(required_columns.size());
     for (const auto & name : required_columns)
     {
-        if (auto * col = input_header.findByName(name))
-            output_header.insert(*col);
-        else if (auto col = table_func_desc->additional_result_columns.tryGetByName(name); col.has_value())
-            output_header.insert(ColumnWithTypeAndName{col->type->createColumn(), col->type, col->name});
+        if (auto * input_col = input_header.findByName(name))
```
Comment (yokofly) [inline src/Storages/Streaming/ProxyStream.cpp]:
```
/src/Storages/Streaming/ProxyStream.cpp:304:23: error: declaration shadows a local variable [-Werror,-Wshadow]
        else if (auto col = table_func_desc->additional_result_columns.tryGetByName(name); col.has_value())
                      ^
/src/Storages/Streaming/ProxyStream.cpp:302:20: note: previous declaration is here
        if (auto * col = input_header.findByName(name))
                   ^
1 error generated.
```

File: src/Storages/Streaming/SeekToInfo.cpp [hunk 25]
```diff
@@ -136,12 +136,12 @@ std::pair<SeekToType, int64_t> doParse(const String & seek_to, bool utc)
     else if (seek_to == "earliest")
         return {SeekToType::SEQUENCE_NUMBER, nlog::EARLIEST_SN};
 
-    if (auto [seek_point, valid] = tryParseRelativeTimeSeek(seek_to, utc); valid)
-        return {SeekToType::RELATIVE_TIME, seek_point};
-    else if (auto [seek_point, valid] = tryParseAbsoluteTimeSeek(seek_to); valid) /// 2020-01-01T01:12:45.123
-        return {SeekToType::ABSOLUTE_TIME, seek_point};
-    else if (auto [seek_point, valid] = tryParseSequenceBasedSeek(seek_to); valid)
-        return {SeekToType::SEQUENCE_NUMBER, seek_point};
+    if (auto [relative_seek_point, relative_valid] = tryParseRelativeTimeSeek(seek_to, utc); relative_valid)
```
Comment (yokofly) [inline src/Storages/Streaming/SeekToInfo.cpp]:
```
src/Storages/Streaming/SeekToInfo.cpp:141:20: error: declaration shadows a structured binding [-Werror,-Wshadow]
    else if (auto [seek_point, valid] = tryParseAbsoluteTimeSeek(seek_to); valid) /// 2020-01-01T01:12:45.123
                   ^
src/Storages/Streaming/SeekToInfo.cpp:139:15: note: previous declaration is here
    if (auto [seek_point, valid] = tryParseRelativeTimeSeek(seek_to, utc); valid)
              ^
src/Storages/Streaming/SeekToInfo.cpp:141:32: error: declaration shadows a structured binding [-Werror,-Wshadow]
    else if (auto [seek_point, valid] = tryParseAbsoluteTimeSeek(seek_to); valid) /// 2020-01-01T01:12:45.123
                               ^
/src/Storages/Streaming/SeekToInfo.cpp:139:27: note: previous declaration is here
    if (auto [seek_point, valid] = tryParseRelativeTimeSeek(seek_to, utc); valid)
                          ^
/src/Storages/Streaming/SeekToInfo.cpp:143:20: error: declaration shadows a structured binding [-Werror,-Wshadow]
    else if (auto [seek_point, valid] = tryParseSequenceBasedSeek(seek_to); valid)
                   ^
/src/Storages/Streaming/SeekToInfo.cpp:141:20: note: previous declaration is here
    else if (auto [seek_point, valid] = tryParseAbsoluteTimeSeek(seek_to); valid) /// 2020-01-01T01:12:45.123
                   ^
/src/Storages/Streaming/SeekToInfo.cpp:143:32: error: declaration shadows a structured binding [-Werror,-Wshadow]
    else if (auto [seek_point, valid] = tryParseSequenceBasedSeek(seek_to); valid)
                               ^
/src/Storages/Streaming/SeekToInfo.cpp:141:32: note: previous declaration is here
    else if (auto [seek_point, valid] = tryParseAbsoluteTimeSeek(seek_to); valid) /// 2020-01-01T01:12:45.123
                               ^
4 errors generated.
````

File: src/Storages/Streaming/StorageRandom.cpp [hunk 26]
```diff
@@ -419,9 +419,9 @@ class GenerateRandomSource final : public ISource
             return doGenerate(block_size);
     }
 
-    Chunk doGenerate(UInt64 block_size)
+    Chunk doGenerate(UInt64 block_size_)
```
Comment (yokofly) [inline src/Storages/Streaming/StorageRandom.cpp]:
```
src/Storages/Streaming/StorageRandom.cpp:422:29: error: declaration shadows a field of 'DB::(anonymous namespace)::GenerateRandomSource' [-Werror,-Wshadow]
    Chunk doGenerate(UInt64 block_size)
                            ^
/src/Storages/Streaming/StorageRandom.cpp:464:12: note: previous declaration is here
    UInt64 block_size;
           ^
```

File: src/V8/Utils.cpp [hunk 27]
```diff
@@ -81,7 +81,7 @@ fillV8Array(v8::Isolate * isolate, const DataTypePtr & arg_type, const MutableCo
         case TypeIndex::UInt8: {
             if (arg_type->getName() == "bool")
             {
-                for (int i = 0; i < size; i++)
+                for (uint64_t i = 0; i < size; i++)
```
Comment (yokofly) [inline src/V8/Utils.cpp]: `size` is uint64_t type. plz check this file L68 
https://github.com/timeplus-io/proton/pull/123/files#diff-8ea7952977155059a02d62a2edd036d580926da68393a08197e2ea0ee96d8dddR68

File: src/V8/V8.cpp [hunk 28]
```diff
@@ -38,10 +38,9 @@ void gcEpilogueCallback(v8::Isolate * isolate, v8::GCType type, v8::GCCallbackFl
     (void)flags;
 }
 
-void oomHandler(const char * location, bool is_heap_oom)
-{
+void OOMCallback(const char* location, const v8::OOMDetails& oom_details) {
     (void)location;
-    (void)is_heap_oom;
+    (void)oom_details;
```
Comment (yokofly) [inline src/V8/V8.cpp]: new api

File: src/V8/V8.cpp [hunk 29]
```diff
@@ -76,7 +75,7 @@ void V8::shutdown()
         return;
 
     v8::V8::Dispose();
-    v8::V8::ShutdownPlatform();
+    v8::V8::DisposePlatform();
```
Comment (yokofly) [inline src/V8/V8.cpp]: new api

File: src/V8/examples/v8_perf.cpp [hunk 30]
```diff
@@ -306,7 +306,7 @@ void run(v8::Isolate * isolate, const v8::Persistent<v8::Context> & obj_blue_pri
     LOG_INFO(v8_log, "took {}us to run {} uda script, us_per_iteration={}", duration, all_states.size(), duration / all_states.size());
 
     /// validate the results
-    auto sum = std::accumulate(values.begin(), values.end(), 0);
+    size_t sum = std::accumulate(values.begin(), values.end(), 0);
```
Comment (yokofly) [inline src/V8/examples/v8_perf.cpp]: L312 does the comparison require the same type

File: src/Storages/Streaming/StorageStream.cpp [hunk 31]
```diff
@@ -1119,13 +1119,13 @@ SinkToStoragePtr StorageStream::write(const ASTPtr & /*query*/, const StorageMet
     return std::make_shared<StreamSink>(*this, metadata_snapshot, context_);
 }
 
-void StorageStream::checkTableCanBeDropped(ContextPtr context) const
+void StorageStream::checkTableCanBeDropped(ContextPtr context_) const
```
Comment (yokofly) [inline src/Storages/Streaming/StorageStream.cpp]:
```
/src/Storages/Streaming/StorageStream.cpp:1122:55: error: parameter 'context' shadows member inherited from type 'WithContextImpl<std::shared_ptr<DB::Context>>' [-Werror,-Wshadow-field]
void StorageStream::checkTableCanBeDropped(ContextPtr context) const
                                                      ^
/src/Interpreters/Context_fwd.h:47:10: note: declared here
    Weak context;
         ^
1 error generated.
```

File: programs/server/Server.cpp [hunk 32]
```diff
@@ -533,7 +533,7 @@ void Server::initV8()
 void Server::disposeV8()
 {
     v8::V8::Dispose();
-    v8::V8::ShutdownPlatform();
+    v8::V8::DisposePlatform();
```
Comment (yokofly) [inline programs/server/Server.cpp]: new api

**Review by qijun-niu-timeplus — APPROVED** [review]
LGTM

**Comment by yokofly** [comment]
above warning is under built with `build.sh`

**Comment by yokofly** [comment]
_edit v1: update latest finding_

edit v1: 
I use the `docker/packager/packger` script locally to build the proton repository, in this branch and the develop branch. 
The develop branch can install correctly, but this branch reports it cannot find config.yaml/grok_pattern related things when installing.
So, does the problem only happen in the build bundle stage?
image

---
original post:
CI failure: not found yaml file..??

image

**Comment by yokofly** [comment]
- [x] https://github.com/ClickHouse/ClickHouse/pull/55147/
- [x] https://github.com/ClickHouse/ClickHouse/pull/42972
- [x] https://github.com/ClickHouse/ClickHouse/pull/51436
- [x] https://github.com/ClickHouse/ClickHouse/pull/49438
- [x] https://github.com/ClickHouse/ClickHouse/pull/42013
- [x] https://github.com/ClickHouse/ClickHouse/pull/42014
- [x] https://github.com/ClickHouse/ClickHouse/pull/55492
- [x] https://github.com/ClickHouse/ClickHouse/pull/51897
- [x] https://github.com/ClickHouse/ClickHouse/pull/49378
- [x] https://github.com/ClickHouse/ClickHouse/pull/35130

also upgrade to newer version `nuraft` `azure-sdk`.

**Review by qijun-niu-timeplus — APPROVED** [review]
