### PR TITLE
checking external stream args

### LINKED ISSUE #289: create external stream without shard_expr will cause proton crash
**Describe what's wrong**

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

```
create stream es(raw int) engine=ExternalStream
```

### PR DESCRIPTION
**Pull request by qijun-niu-timeplus**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

```
CREATE STREAM es
(`raw` int
)
ENGINE = ExternalStream
```

throw exception

```
Code: 36. DB::Exception: Received from localhost:8463. DB::Exception: ExternalStream requires sharding key expression. (BAD_ARGUMENTS)
```

### CODE REVIEW

**Review by yokofly — APPROVED** [review]

File: src/Storages/ExternalStream/StorageExternalStream.cpp [hunk 1]
```diff
@@ -39,6 +39,9 @@ buildShardingKeyExpression(ASTPtr sharding_key, ContextPtr context, const NamesA
 }
 
 void validateEngineArgs(ContextPtr context, ASTs & engine_args, const ColumnsDescription & columns) {
+    if (engine_args.size() == 0)
+        throw Exception(ErrorCodes::BAD_ARGUMENTS, "ExternalStream requires sharding key expression");
+
```
Comment (yl-lisen) [inline src/Storages/ExternalStream/StorageExternalStream.cpp:44]: A better way is that when no specified sharing key expression, use a default shading expression `rand()`

Comment (mrssss) [reply src/Storages/ExternalStream/StorageExternalStream.cpp:44]: resolved

**Review by yl-lisen — APPROVED** [review]
