### PR TITLE
before cast we shall check existed or not.

### LINKED ISSUE #799: nullptr access when window function work on streaming query
**Describe what's wrong**
```
 create stream v(id int);
 select sum(id) over w1 from v window w1 as ();
 ```

### PR DESCRIPTION
**Pull request by yokofly**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:
fix #799

### CODE REVIEW

File: tests/queries_ported/0_stateless/99003_window_function.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+drop stream if exists v;
```
Comment (yl-lisen) [inline tests/queries_ported/0_stateless/99003_window_function.sql:1]: file name `99003...` was existed, you need reassign different number

Comment (yokofly) [reply tests/queries_ported/0_stateless/99003_window_function.sql:1]: I only find the 99002 used
https://github.com/search?q=repo%3Atimeplus-io%2Fproton+99002&type=code
https://github.com/search?q=repo%3Atimeplus-io%2Fproton+99003&type=code

**Review by yl-lisen — APPROVED** [review]
