### PR TITLE
Bugfix/issue 320 fix tsan

### LINKED ISSUE #320: fix tsan(thread sanitizer) (fail in startup proton server)
**Describe what's wrong**

**How to reproduce**

**Error message and/or stacktrace**

```c++
2023.11.21 03:27:41.091928 [ 948778 ] {} <Information> Context: Initialized background executor for merges and mutations with num_threads=16, num_tasks=32
2023.11.21 03:27:41.094445 [ 948778 ] {} <Information> Context: Initialized background executor for move operations with num_threads=8, num_tasks=8
2023.11.21 03:27:41.096489 [ 948778 ] {} <Information> Context: Initialized background executor for fetches with num_threads=8, num_tasks=8
2023.11.21 03:27:41.098022 [ 948778 ] {} <Information> Context: Initialized background executor for common operations (e.g. clearing old parts) with num_threads=8, num_tasks=8
2023.11.21 03:27:41.099168 [ 948778 ] {} <Information> Application: Loading metadata from ./
2023.11.21 03:27:41.102572 [ 948778 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2023.11.21 03:27:41.141794 [ 948778 ] {} <Warning> ExternalGrokPatterns: External grok patterns file 'grok-patterns' does not exist, trying embedded resource
2023.11.21 03:27:41.194493 [ 948778 ] {} <Warning> TelemetryCollector: Please note that telemetry is enabled. This is used to collect the version and runtime environment information to Timeplus, Inc. You can disable it by setting telemetry_enabled to false in config.yaml
2023.11.21 03:27:41.196333 [ 949069 ] {} <Information> LocalFileSystemCheckpoint: Scanning delete-marked and expired checkpoints in checkpoint directory=0835/var/lib/proton/checkpoint/, ttl=604800s
2023.11.21 03:27:41.196966 [ 948778 ] {} <Information> NativeLog: NativeLog init with configs: meta_dir=0835/var/lib/proton/nativelog/meta/ log_dirs=0835/var/lib/proton/nativelog/log check_crcs=false max_schedule_threads=8 max_adhoc_schedule_threads=8 max_cached_entries=10000 max_cached_bytes=419430400 max_cached_entries_per_shard=100 max_cached_bytes_per_shard=4194304 max_wait_ms=500 max_bytes=65536 max_record_size=10485760 segment_size=4294967296 segment_ms=604800000 flush_interval_records=1000 flush_interval_ms=120000 retention_size=-1 retention_ms=604800000 file_delete_delay_ms=300000 max_index_size=10485760 index_interval_bytes=4096 index_interval_records=1000 preallocate=true recovery_threads_per_data_dir=1 flush_check_ms=4294967295 flush_recovery_sn_checkpoint_ms=60000 flush_start_sn_checkpoint_ms=60000 retention_check_ms=300000 num_threads=1 dedup_buffer_size=4194304 dedup_load_factor=0.9 io_buffer_size=1048576 max_io_bytes_per_second=1.7976931348623157e+308 backoff_ms=15000 enable_compactor=true hash_algo=MD5
2023.11.21 03:27:41.197032 [ 948778 ] {} <Information> BackgroundSchedulePool/NLogSched: Create BackgroundSchedulePool with 8 threads
2023.11.21 03:27:41.200559 [ 948778 ] {} <Information> NativeLog: Starting
Process 948778 stopped
* thread #125, name = 'BgSchPool', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
(lldb) bt
* thread #125, name = 'BgSchPool', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x0000000009fd7554 proton-server`__interceptor___dn_expand + 260
    frame #2: 0x00007ffff6403806 libnss_dns.so.2`___lldb_unnamed_symbol66 + 1046
    frame #3: 0x00007ffff640532f libnss_dns.so.2`_nss_dns_gethostbyname4_r + 783
    frame #4: 0x00007ffff7e8b40f libc.so.6`___lldb_unnamed_symbol3035 + 3903
    frame #5: 0x00007ffff7e8cf59 libc.so.6`getaddrinfo + 297
    frame #6: 0x0000000009fc75ab proton-server`__interceptor_getaddrinfo + 251
    frame #7: 0x00000000238563cd proton-server`Poco::Net::DNS::hostByName(hostname="data.timeplus.com", hintFlags=34) at DNS.cpp:79:11
    frame #8: 0x0000000023894f06 proton-server`Poco::Net::SocketAddress::init(this=0x00007ffe7c0f5268, hostAddress="data.timeplus.com", portNumber=443) at SocketAddress.cpp:269:18
    frame #9: 0x0000000023894e37 proton-server`Poco::Net::SocketAddress::SocketAddress(this=0x00007ffe7c0f5268, hostAddress="data.timeplus.com", portNumber=443) at SocketAddress.cpp:104:2
    frame #10: 0x0000000023860084 proton-server`Poco::Net::HTTPClientSession::reconnect(this=0x00007ffe7c0f5458) at HTTPClientSession.cpp:417:17
    frame #11: 0x000000002385efe5 proton-server`Poco::Net::HTTPClientSession::sendRequest(this=0x00007ffe7c0f5458, request=0x00007ffe7c0f5650) at HTTPClientSession.cpp:244:4
    frame #12: 0x000000001205661d proton-server`DB::TelemetryCollector::collect(this=0x00000000256581f0) at TelemetryCollector.cpp:133:40
    frame #13: 0x0000000012057902 proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0, void ()>>(std::__1::__function::__policy_storage const*) [inlined] DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0::operator()(this=<unavailable>) const at TelemetryCollector.cpp:52:77
    frame #14: 0x00000000120578fd proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0, void ()>>(std::__1::__function::__policy_storage const*) [inlined] decltype(std::declval<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0&>(__f=<unavailable>) at invoke.h:394:23
    frame #15: 0x00000000120578fd proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0, void ()>>(std::__1::__function::__policy_storage const*) [inlined] void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0&>(__args=<unavailable>) at invoke.h:479:9
    frame #16: 0x00000000120578fd proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0, void ()>>(std::__1::__function::__policy_storage const*) [inlined] std::__1::__function::__default_alloc_func<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0, void ()>::operator()[abi:v15000](this=<unavailable>) at function.h:235:12
    frame #17: 0x00000000120578fd proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TelemetryCollector::TelemetryCollector(std::__1::shared_ptr<DB::Context const>)::$_0, void ()>>(__buf=0x00007b3400005f58) at function.h:716:16
    frame #18: 0x00000000197e1ad3 proton-server`DB::BackgroundSchedulePoolTaskInfo::execute() [inlined] std::__1::__function::__policy_func<void ()>::operator()[abi:v15000](this=0x00007b3400005f58) const at function.h:848:16
    frame #19: 0x00000000197e1ac1 proton-server`DB::BackgroundSchedulePoolTaskInfo::execute() [inlined] std::__1::function<void ()>::operator()(this=0x00007b3400005f58) const at function.h:1187:12
    frame #20: 0x00000000197e1ac1 proton-server`DB::BackgroundSchedulePoolTaskInfo::execute(this=0x00007b3400005f28) at BackgroundSchedulePool.cpp:105:5
    frame #21: 0x00000000197e419c proton-server`DB::BackgroundSchedulePool::threadFunction() [inlined] DB::TaskNotification::execute(this=0x00007b08000efd60) at BackgroundSchedulePool.cpp:18:28
    frame #22: 0x00000000197e418a proton-server`DB::BackgroundSchedulePool::threadFunction(this=0x00007b4800004500) at BackgroundSchedulePool.cpp:261:31
    frame #23: 0x00000000197e4a06 proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0::operator()(this=<unavailable>) const at BackgroundSchedulePool.cpp:151:48
    frame #24: 0x00000000197e49fe proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&>(__f=<unavailable>) at invoke.h:394:23
    frame #25: 0x00000000197e49fe proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&, std::__1::tuple<>&>(__f=<unavailable>, __t=<unavailable>, (null)=<unavailable>) at tuple:1789:1
    frame #26: 0x00000000197e49fe proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] decltype(auto) std::__1::apply[abi:v15000]<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&, std::__1::tuple<>&>(__f=<unavailable>, __t=<unavailable>) at tuple:1798:1
    frame #27: 0x00000000197e49fe proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(this=0x00007b0800057700)::$_0&&)::'lambda'()::operator()() at ThreadPool.h:205:13
    frame #28: 0x00000000197e49c5 proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] decltype(std::declval<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'()&>(__f=0x00007b0800057700) at invoke.h:394:23
    frame #29: 0x00000000197e49c5 proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'()&>(__args=0x00007b0800057700) at invoke.h:479:9
    frame #30: 0x00000000197e49c5 proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) [inlined] std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000](this=0x00007b0800057700) at function.h:235:12
    frame #31: 0x00000000197e49c5 proton-server`void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_0&&)::'lambda'(), void ()>>(__buf=<unavailable>) at function.h:716:16
    frame #32: 0x00000000120400d6 proton-server`ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) [inlined] std::__1::__function::__policy_func<void ()>::operator()[abi:v15000](this=0x00007ffe7c0f5fa8) const at function.h:848:16
    frame #33: 0x00000000120400cf proton-server`ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) [inlined] std::__1::function<void ()>::operator()(this=0x00007ffe7c0f5fa8) const at function.h:1187:12
    frame #34: 0x00000000120400cf proton-server`ThreadPoolImpl<std::__1::thread>::worker(this=0x00007b4400007e40, thread_it=std::__1::list<std::__1::thread, std::__1::allocator<std::__1::thread> >::iterator @ 0x00007ffe7c0f5f20) at ThreadPool.cpp:393:13
    frame #35: 0x0000000012044352 proton-server`void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) [inlined] void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(this=<unavailable>)>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const at ThreadPool.cpp:168:73
    frame #36: 0x000000001204433d proton-server`void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) [inlined] decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(__f=<unavailable>) at invoke.h:394:23
    frame #37: 0x000000001204433d proton-server`void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) [inlined] void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(__t=size=2, (null)=<unavailable>) at thread:284:5
    frame #38: 0x000000001204433d proton-server`void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(__vp=0x00007b0800057720) at thread:295:5
    frame #39: 0x0000000009fbe3af proton-server`__tsan_thread_start_func + 175
    frame #40: 0x00007ffff7f81609 libpthread.so.0`start_thread + 217
    frame #41: 0x00007ffff7ea6133 libc.so.6`__clone + 67
(lldb) 

```

### PR DESCRIPTION
**Pull request by yokofly**
_edit v1: update more pr info_ 

Please write user-readable short description of the changes:
fix #320 
stacktrace here:
1. when quit proton-server muduo timeservice data race [stack trace here](https://github.com/timeplus-io/proton/issues/320#issuecomment-1821966387)
2. run smoke test: docheckpoint data race [stack trace here](https://github.com/timeplus-io/proton/issues/320#issuecomment-1821969630)

useful link:
https://en.cppreference.com/w/cpp/atomic/atomic/wait
https://www.youtube.com/watch?v=gTpubZ8N0no

### CODE REVIEW

File: src/Common/TimerService.h [hunk 1]
```diff
@@ -26,6 +28,7 @@ class TimerService final
     /// Safe to call from other threads.
     muduo::net::TimerId runAfter(double delay, muduo::net::TimerCallback cb)
     {
+        std::scoped_lock lock(event_loop_mutex);
         assert(event_loop);
         return event_loop->runAfter(delay, std::move(cb));
```
Comment (yl-lisen) [inline src/Common/TimerService.h]: After TimerService shutdown, the event_loop is nullptr, but it still may be called in `CheckpointCoordinator::removeExpiredCheckpoints` ?

Comment (yl-lisen) [reply src/Common/TimerService.h]: We can make the class `TimerService` is thread safe, or we can also ensure it where used

Comment (yokofly) [reply src/Common/TimerService.h]: that's the reason I added a lock guard here, and checked the pointer exists in the shutdown function.
Do you mean we need to check the pointer exists before calling the function in the `runAfter` ? 
```
void TimerService::shutdown()
{
    {
        std::scoped_lock lock(event_loop_mutex);
        if (event_loop)
        {
            event_loop->quit();

            /// Decrement ref count to make sure the last ref count
            /// of event loop is in the creation thread
            event_loop = nullptr;
        }
    }

    eloop_init_guard.store(nullptr);
    eloop_init_guard.notify_all();

    looper.wait();
}
```

Comment (yl-lisen) [reply src/Common/TimerService.h]: yes, as above mentioned that when quit proton-server muduo timeservice data race https://github.com/timeplus-io/proton/issues/320#issuecomment-1821966387 ,
One thread is calling  `TimerService::shutdown()` in `~CheckpointCoordinator()`
Another thread is calling `TimerService::runAfter()` (belongs to EventLoop thread)

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp [hunk 2]
```diff
@@ -161,13 +168,14 @@ Chunk StreamingStoreSourceBase::generate()
...
+/// We need make sure it is thread safe
 void StreamingStoreSourceBase::checkpoint(CheckpointContextPtr ckpt_ctx_)
 {
     /// We assume the previous ckpt is already done
     /// Use std::atomic<std::shared_ptr<CheckpointContext>>
-    assert(!ckpt_ctx.load(std::memory_order_relaxed));
-    ckpt_ctx = new CheckpointContext(*ckpt_ctx_);
+    std::scoped_lock lock(ckpt_mutex);
+    assert(!ckpt_ctx);
+    ckpt_ctx = std::make_shared<CheckpointContext>(*ckpt_ctx_);
```
Comment (yl-lisen) [inline src/Storages/Streaming/StreamingStoreSourceBase.cpp]: I want to know why the previous one was wrong?

Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: https://github.com/timeplus-io/proton/issues/320#issuecomment-1821969630
one thread alloc/write by `new`
one thread is access/read with `doCheckpoint`

Comment (yl-lisen) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: It's an atomic variable, so why does this problem arise?

Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: I try many times in my local with my assumption, but do not get a thread sanitizer report(hahaha).

basically, I believe the problem is `ckpt_ctx = new CheckpointContext(*ckpt_ctx_);`
this phase has done 2 things:
the first step is new a object, then the second step will be atomically assigned.

the key is: thread 2(t2) may read old_obj, in the same time ckpt_ctx has been assigning with new_obj in thread 1(t1)
the pointer is safe, but the pointer reference object is not guaranteed. 
with a mutex lock guard, the  t1's new and assign operations are seen as a single, atomic action from t2's perspective.

```
// from gpt
[Thread 1 - Writer]                              [Thread 2 - Reader]
   |                                                   |
   |--- (1) new_obj = new CheckpointContext(...) -----|  // Creates a new object (deep copy)
   |                                                   |
   |--- (2) ckpt_ctx = new_obj -----------------------|  // Atomically assigns the new object's
   |        (Atomic assignment)                        |  // address to ckpt_ctx.
   |                                                   |
   |===================== DATA RACE ===================|
   |                                                   |
   |                                                   |--- (3) current = ckpt_ctx.exchange(nullptr)
   |                                                   |     (Atomic exchange)
   |                                                   |
   |--- (4) Return from function ----------------------|  // Thread 1 completes its operation.
   |                                                   |     // Thread 2 may now be working with
   |                                                   |     // the object previously pointed to by
   |                                                   |     // ckpt_ctx.

```

**Comment by yokofly** [comment]
may follow up https://github.com/timeplus-io/proton/pull/111

File: src/Common/TimerService.cpp [hunk 3]
```diff
@@ -12,12 +12,19 @@ void TimerService::startup()
...
+    {
+        std::scoped_lock lock(event_loop_mutex);
+        if (event_loop)
+        {
+            event_loop->quit();
+
+            /// Decrement ref count to make sure the last ref count
+            /// of event loop is in the creation thread
+            event_loop = nullptr;
+        }
```
Comment (chenziliang) [inline src/Common/TimerService.cpp]: if event_loop is nullptr, we shall return directly ?

File: src/Common/TimerService.h [hunk 4]
```diff
@@ -18,31 +24,47 @@ class TimerService final
     /// Safe to call from other threads.
     muduo::net::TimerId runAt(muduo::Timestamp time, muduo::net::TimerCallback cb)
     {
-        assert(event_loop);
+        std::scoped_lock lock(event_loop_mutex);
```
Comment (chenziliang) [inline src/Common/TimerService.h]: I think we shall avoid using lock here since runAt is thread safe. Even event_loop itself is not thread safe, we require users to align `shutdown` and `runAt` which means shutdown is only invoked when system is going down and after that we shall never call `runAt`. If we do, there is logic error.

Comment (chenziliang) [reply src/Common/TimerService.h]: This is why i ask if we can just mask TSAN for TimerService ? which means don't apply TSA to TimerService since we know what we are doing and for now, it seems not quite worth fixing it since we will decommission it.

File: src/Storages/Streaming/StreamingStoreSourceBase.h [hunk 5]
```diff
@@ -50,7 +50,8 @@ class StreamingStoreSourceBase : public ISource
 
     Int64 last_sn = -1;
     Int64 last_epoch = -1;
-    /// FIXME, switch to llvm-15
-    std::atomic<CheckpointContext *> ckpt_ctx;
+    /// FIXME, switch to llvm-15 atomic shared_ptr
+    CheckpointContextPtr ckpt_ctx TSA_PT_GUARDED_BY(ckpt_mutex);
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.h]: 1. In general (general guideline), `mutex` shall be defined before the data members it protects since when dtor, data members will be dtor first and then mutex and this is safer in different scenarios. 
2. There is race condition, this is exactly why we have a `FIXME`. Can you try if `std::atomic<CheckpointContextPtr>` works ? And for now, we tolerate this race because they are usually scheduled at least seconds if not mins away. So in practice, it may not quite matter. Having said this, can you try `std::atomic<CheckpointContextPtr>`

Comment (chenziliang) [reply src/Storages/Streaming/StreamingStoreSourceBase.h]: We are trying to avoid a mutex here since it is in hot path.

Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.h]: _edit v1: update the compiler link_
I know, but even in clang-17 the compiler still does not support it.

see below the online compiler:
https://godbolt.org/z/aGaEPbEc7
or check this compiler support in cppref:
https://en.cppreference.com/w/cpp/compiler_support#:~:text=Atomic%20std%3A%3Ashared_ptr,19.27*

File: src/Storages/Streaming/StreamingStoreSourceBase.h [hunk 6]
```diff
@@ -50,7 +50,8 @@ class StreamingStoreSourceBase : public ISource
...
+    std::mutex ckpt_mutex;
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.h]: We may need apply 
1) fast mutex 
2) double checked locking to avoid lock a mutex always.

```
FastMutext ckpt_mutex;
std::atomic<bool> has_ckpt_request = false;
```

```
/// Check
{
    CheckpointContextPtr ckpt;
    if (has_ckpt_request)
    {
        std::scope_lock lock(ckpt_mutex);
        if (ckpt_ctx)
        {
            ckpt.swap(ckpt_ctx); <-- use swap probably faster ?
            has_ckpt_request = false;
        }
    }
}


/// Set
{
    std::scope_lock lock(ckpt_mutex);
    /// ckpt coordinator guarantees that ckpt is not overlapped.
    assert(!has_ckpt_request);
    assert(!ckpt_ctx);
    ckpt_ctx = std::make_shared<CheckpointContext>(*ckpt_ctx_);
    has_ckpt_request = true;
}
```

Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.h]: this is just a demo about mutex and atomicbool check.not ready merge.

micro benchmark I will
do in later . 

I intend to use atomic<ckpt*> and std mutex.

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp [hunk 7]
```diff
@@ -161,13 +171,20 @@ Chunk StreamingStoreSourceBase::generate()
...
-/// We nee make sure it is thread safe
+/// We need make sure it is thread safe
 void StreamingStoreSourceBase::checkpoint(CheckpointContextPtr ckpt_ctx_)
 {
     /// We assume the previous ckpt is already done
     /// Use std::atomic<std::shared_ptr<CheckpointContext>>
-    assert(!ckpt_ctx.load(std::memory_order_relaxed));
-    ckpt_ctx = new CheckpointContext(*ckpt_ctx_);
+    assert(!has_ckpt_request);
+    CheckpointContextPtr new_ckpt = std::make_shared<CheckpointContext>(*ckpt_ctx_);
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.cpp]: Do we need make a new_ckpt ?

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp [hunk 8]
```diff
@@ -138,8 +138,18 @@ Chunk StreamingStoreSourceBase::generate()
...
-    if (auto * current = ckpt_ctx.exchange(nullptr, std::memory_order_relaxed); current)
-        return doCheckpoint(CheckpointContextPtr{current});
+    CheckpointContextPtr current;
+    if (has_ckpt_request)
+    {
+        {
+            std::scoped_lock lock(ckpt_mutex);
+            current.swap(ckpt_ctx);
+        }
+        has_ckpt_request = false;
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.cpp]: We will need set it under ckpt_mutex held.

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp [hunk 9]
```diff
@@ -138,8 +138,18 @@ Chunk StreamingStoreSourceBase::generate()
     if (isCancelled())
         return {};
 
-    if (auto * current = ckpt_ctx.exchange(nullptr, std::memory_order_relaxed); current)
-        return doCheckpoint(CheckpointContextPtr{current});
+    CheckpointContextPtr current;
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.cpp]: `current` -> `current_ckpt_ctx`

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp [hunk 10]
```diff
@@ -138,8 +138,18 @@ Chunk StreamingStoreSourceBase::generate()
...
+    {
+        {
+            std::scoped_lock lock(ckpt_mutex);
+            current.swap(ckpt_ctx);
+        }
+        has_ckpt_request = false;
+    }
+
+    if (current)
+        return doCheckpoint(current);
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.cpp]: `std::move(current)`

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp [hunk 11]
```diff
@@ -161,13 +171,20 @@ Chunk StreamingStoreSourceBase::generate()
...
-    ckpt_ctx = new CheckpointContext(*ckpt_ctx_);
+    assert(!has_ckpt_request);
+    CheckpointContextPtr new_ckpt = std::make_shared<CheckpointContext>(*ckpt_ctx_);
+
+    {
+        std::scoped_lock lock(ckpt_mutex);
+        assert(!ckpt_ctx);
+        ckpt_ctx.swap(new_ckpt);
+    }
+    has_ckpt_request = true;
```
Comment (chenziliang) [inline src/Storages/Streaming/StreamingStoreSourceBase.cpp]: We will need set it with ckpt_mutex held.

File: src/Storages/Streaming/benchmarks/atomic_lock_double_check_perf.cpp [hunk 12]
```diff
@@ -0,0 +1,145 @@
...
+
+
+class ComplexSharedResource
+{
+    [[maybe_unused]] std::list<int> lst;
+    [[maybe_unused]] std::list<int>::iterator itor;
+    [[maybe_unused]] int valid_num;
+};
+
+static void BM_ScopedLockOnly(benchmark::State & state)
```
Comment (chenziliang) [inline src/Storages/Streaming/benchmarks/atomic_lock_double_check_perf.cpp]: Consider anonymous namespace instead of static

Comment (chenziliang) [reply src/Storages/Streaming/benchmarks/atomic_lock_double_check_perf.cpp]: like 

```
namespace
{
..
}

BENCHMARK(BM_ScopedLockOnly)->MinTime(3);
BENCHMARK(BM_AtomicWithScopedLockOnPocoFastMutex)->MinTime(3);
```

Comment (yokofly) [reply src/Storages/Streaming/benchmarks/atomic_lock_double_check_perf.cpp]: i see. tks

File: src/NativeLog/Log/Log.h [hunk 13]
```diff
@@ -304,7 +304,7 @@ class Log final : private boost::noncopyable
 
     std::atomic_flag closed;
 
-    bool inmemory = false;
+    std::atomic<bool> inmemory = false;
```
Comment (chenziliang) [inline src/NativeLog/Log/Log.h]: Why this need to be atomic since it is set once during ctor and read-only afterwards ?

Comment (yokofly) [reply src/NativeLog/Log/Log.h]: the boolean var also report by thread sanitizer,  basically the usage(read) does not been guarantee the thread safety.

File: src/Storages/ExternalStream/Kafka/KafkaSource.h [hunk 14]
```diff
@@ -87,8 +87,10 @@ class KafkaSource final : public ISource
     Int32 record_consume_timeout_ms = 100;
 
     /// For checkpoint
-    /// FIXME, switch to llvm-15
-    std::atomic<CheckpointContext *> ckpt_ctx;
+    /// FIXME, switch to llvm-15 atomic shared_ptr
```
Comment (chenziliang) [inline src/Storages/ExternalStream/Kafka/KafkaSource.h]: We can consider refactor it out as a util struct like below and reuse everywhere ?

```
/// \CheckpointRequest applies double check locking to minimize using mutex 
/// directly for better performance
class CheckpointRequest
{
public:
    /// \poll moves out the existing checkpoint context request atomically if there is any.
    CheckpointContextPtr poll() noexcept 
    { 
        CheckpointContextPtr new_request;
        if (has_ckpt_request)
        {
            std::scoped_lock lock(ckpt_mutex);
            new_request.swap(ckpt_ctx);
            has_ckpt_request = false;
        }
        return new_request;
    }

     void setCheckpointRequestCtx(CheckpointContextPtr ckpt_ctx_) noexcept
     {
         assert(!has_ckpt_request);
         std::scoped_lock lock(ckpt_mutex);
         assert(!ckpt_ctx);
         ckpt_ctx.swap(ckpt_ctx_);
         has_ckpt_request = true;
     }

     bool hasRequest() const noexcept { return has_ckpt_request; }

private:
    std::atomic<bool> has_ckpt_request = false;
    std::mutex ckpt_mutex;
    CheckpointContextPtr ckpt_ctx TSA_PT_GUARDED_BY(ckpt_mutex);
};
```

Comment (chenziliang) [reply src/Storages/ExternalStream/Kafka/KafkaSource.h]: Place this util class in the same directory as where `CheckpointContext` is defined

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp (hunk 8 above)
Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: why? Does Atomic Value also need a mutex guard?

File: src/NativeLog/Log/Log.h (hunk 13 above)
Comment (chenziliang) [reply src/NativeLog/Log/Log.h]: Interesting. Can we mask this variable to avoid the TSA ?

Comment (yokofly) [reply src/NativeLog/Log/Log.h]: https://github.com/timeplus-io/proton/issues/320#issuecomment-1842414990

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp (hunk 8 above)
Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: discussed internally:
```
This is a race case.
Thr1: check if having ckpt req -> true -> hold mutex -> swap ckpt -> unlock mutex => at this very time schedule ckpt set thread
Thr2: set checkpoint ctx -> hold mutex -> swap ctx -> unlock mutex -> set has_req bool to true => context switch to Thr1
Thr1: -> set the has_req bool to false. Now we missed handling one request context req
```

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp (hunk 7 above)
Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: i got many many error about the ckpt file path duplicate(i assume this is due to the shallow copy)
work with deep copy everything well.

File: src/Checkpoint/CheckpointRequest.h [hunk 15]
```diff
@@ -0,0 +1,54 @@
...
+            has_ckpt_request.store(false);
+        }
+        return new_request;
+    }
+
+    void setCheckpointRequestCtx(CheckpointContextPtr ckpt_ctx_) noexcept
+    {
+        assert(!has_ckpt_request);
+        /// Perform a deep copy to ensure that the checkpoint file is stored in a distinct path.
+        CheckpointContextPtr new_ckpt = std::make_shared<CheckpointContext>(*ckpt_ctx_);
```
Comment (chenziliang) [inline src/Checkpoint/CheckpointRequest.h]: I don't think we will need a deep copy ?

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp (hunk 7 above)
Comment (chenziliang) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: Could you elaborate the error ? When it happened and what's the exact error message ?

File: src/Checkpoint/CheckpointRequest.h (hunk 15 above)
Comment (yokofly) [reply src/Checkpoint/CheckpointRequest.h]: it works with shallow copy today.. but I remembered yesterday if I do not take the deep copy, the smoke test will break.
and I find the original atomic<ckpt_ctx*> also does deep copy, thus I take this trial.

File: src/Storages/Streaming/StreamingStoreSourceBase.cpp (hunk 7 above)
Comment (yokofly) [reply src/Storages/Streaming/StreamingStoreSourceBase.cpp]: it works with shallow copy today.. but I remembered yesterday if I do not take the deep copy, the smoke test will break.
and I find the original `atomic<ckpt_ctx*>` also does deep copy, thus I take this trial.

**Review by chenziliang — APPROVED** [review]
