### PR TITLE
replay function supports specified column

### LINKED ISSUE #661: Cannot replay from VersionedKV
**Describe what's wrong**

```sql
SELECT
  *
FROM
  stock
SETTINGS
  seek_to = 'earliest', enable_backfill_from_historical_store = 0, replay_speed = 1

Query id: 234a1979-0ed7-4b8a-acfb-d2c8e2287edc


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 2.0.32):
Code: 10. DB::Exception: Received from 127.0.0.1:8463. DB::Exception: Column `_tp_append_time` not found in stream default.stock (2c307eb0-bf01-4975-a62f-b102f496f274). (NOT_FOUND_COLUMN_IN_BLOCK)
```
**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by lizhou1111**
Replay function supports specified column.
For example:
```sql
drop stream if exists test_rep;
create stream if not exists test_rep(id int, time_col datetime64(3));
insert into test_rep(id, time_col) values (1, '2020-02-02 20:01:14')(2, '2020-02-02 20:01:15')(3, '2020-02-02 20:01:17')(4, '2020-02-02 20:01:20');
select *, from test_rep where _tp_time > earliest_timestamp() settings replay_speed=1, replay_time_column='time_col'
```
You have to specify the replay time column in the query through the `replay_time_column` settings

### CODE REVIEW

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 1]
```diff
@@ -2396,6 +2396,7 @@ void InterpreterSelectQuery::executeFetchColumns(QueryProcessingStage::Enum proc
             }
             assert(storagestream);
 
+            const String & replay_time_col = settings.replay_time_column;
             if (std::ranges::none_of(required_columns, [](const auto & name) { return name == ProtonConsts::RESERVED_APPEND_TIME; }))
                 required_columns.emplace_back(ProtonConsts::RESERVED_APPEND_TIME);
```
Comment (yl-lisen) [inline src/Interpreters/InterpreterSelectQuery.cpp]: use `replay_time_col` instead of prev `_tp_append_time` ?

Comment (yl-lisen) [reply src/Interpreters/InterpreterSelectQuery.cpp]: also need validate the replay_time_col is exists in stream (virtual column or physical column)

File: src/Processors/Streaming/ReplayStreamTransform.cpp [hunk 2]
```diff
@@ -16,34 +16,145 @@ namespace Streaming
...
     , last_sn(last_sn_)
     , enable_replay(last_sn >= 0)
+    , replay_time_col(replay_time_col_)
 {
-    append_time_index = header.getPositionByName(ProtonConsts::RESERVED_APPEND_TIME);
+    time_index = header.getPositionByName(replay_time_col);
+    auto & type = header.getByPosition(time_index).type;
+    /// user defined replay_time_col must be DateTime64
+    if (replay_time_col != ProtonConsts::RESERVED_APPEND_TIME && !isDateTime64(type))
+        throw Exception(
```
Comment (yl-lisen) [inline src/Processors/Streaming/ReplayStreamTransform.cpp]: check the column and its datatype  as early as possible

File: src/Processors/Streaming/ReplayStreamTransform.cpp [hunk 3]
```diff
@@ -16,34 +16,145 @@ namespace Streaming
...
+        if (columns[time_index]->getInt(index) != columns[time_index]->getInt(cur_index))
+        {
+            cut_into_chunks(cur_index, index);
+            cur_index = index;
+        }
+        ++index;
+    }
+
+    cut_into_chunks(cur_index, index);
+    input_chunk.clear();
```
Comment (yl-lisen) [inline src/Processors/Streaming/ReplayStreamTransform.cpp:70]: we can add a fast path here, `if (first_row_time == last_row_time) output_chuks.push_back(original);`

File: src/Processors/Streaming/ReplayStreamTransform.cpp [hunk 4]
```diff
@@ -16,34 +16,145 @@ namespace Streaming
...
+
+    /// proton: starts.
+    auto start_ns = MonotonicNanoseconds::now();
+    metrics.processed_bytes += input_data.chunk.bytes();
+    /// proton: ends.
+    try
+    {
+        if (enable_replay && input_data.chunk.rows() && output_chunks.empty())
+            cutChunk(input_data.chunk);
+        transform(input_data.chunk, output_data.chunk);
```
Comment (yl-lisen) [inline src/Processors/Streaming/ReplayStreamTransform.cpp]: For `cutChunk()`, which split the input_data.chunk into output_chunks,  which is not a good function name.
 why not move the `cutChunk` into `transform()` ?

File: src/Processors/Streaming/ReplayStreamTransform.cpp [hunk 5]
```diff
@@ -16,34 +16,145 @@ namespace Streaming
...
 
+    if (wait_interval_ms < 0)
+        throw Exception(
+            fmt::format(
+                "Unoreded data checked, ReplayStreamTransform need ordered data, replay_time_col: {}, last_batch_time: {}, "
+                "this_batch_time: {}",
+                this->replay_time_col,
+                this->last_batch_time.value(),
+                this_batch_time),
+            ErrorCodes::LOGICAL_ERROR);
```
Comment (yl-lisen) [inline src/Processors/Streaming/ReplayStreamTransform.cpp]:
```c++
throw Exception(ErrorCodes::LOGICAL_ERROR, "Found unordered replay timestamp '{}', current_ts: {}, last_ts: {}", this->replay_time_col, this_batch_time, last_batch_time.value());
```

File: tests/stream/test_stream_smoke/0028_replay_stream.yaml [hunk 6]
```diff
@@ -331,4 +331,74 @@ tests:
...
+            wait: 1
+            query: select id, (abs(date_diff('millisecond',lag(now64(), 1), now64()) - date_diff('millisecond', lag(time_col, 1), time_col)) < 20) as interval from test29_stream2
+
+          - client: python
+            query_type: table
+            depends_on: '2906'
+            exist: test29_mv
+            exist_wait: 2
+            wait: 1
+            query: create materialized view if not exists test29_mv into test29_stream2 as (select id, time_col from test29_stream where _tp_time > earliest_timestamp() settings replay_speed=1, replay_time_column='time_col');
```
Comment (yl-lisen) [inline tests/stream/test_stream_smoke/0028_replay_stream.yaml:388]: this case cannot verify if replay behavior is correct

File: src/Processors/Streaming/ReplayStreamTransform.cpp [hunk 7]
```diff
@@ -16,34 +16,145 @@ namespace Streaming
...
     , enable_replay(last_sn >= 0)
+    , replay_time_col(replay_time_col_)
 {
-    append_time_index = header.getPositionByName(ProtonConsts::RESERVED_APPEND_TIME);
+    time_index = header.getPositionByName(replay_time_col);
+    auto & type = header.getByPosition(time_index).type;
+    /// user defined replay_time_col must be DateTime64
+    if (replay_time_col != ProtonConsts::RESERVED_APPEND_TIME && !isDateTime64(type))
+        throw Exception(
+            fmt::format("ReplayStreamTransform need datatime64 type column, but got {}", type->getName()), ErrorCodes::LOGICAL_ERROR);
```
Comment (yl-lisen) [inline src/Processors/Streaming/ReplayStreamTransform.cpp]: it's invalid settings `replay_time_column` , please use  `ErrorCodes::INVALID_SETTING_VALUE`

File: src/Processors/Streaming/ReplayStreamTransform.cpp (hunk 5 above)
Comment (yl-lisen) [reply src/Processors/Streaming/ReplayStreamTransform.cpp]: always use this exception format `Exception(err_code, "...{}...", value)`

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 8]
```diff
@@ -2377,39 +2377,11 @@ void InterpreterSelectQuery::executeFetchColumns(QueryProcessingStage::Enum proc
...
-                required_columns.emplace_back(ProtonConsts::RESERVED_EVENT_SEQUENCE_ID);
-
+            auto last_sns = checkReplaySettingsAndGetLastSN();
             storage->read(
                 query_plan, required_columns, storage_snapshot, query_info, context, processing_stage, max_block_size, max_streams);
-
             auto replay_step = std::make_unique<Streaming::ReplayStreamStep>(
-                query_plan.getCurrentDataStream(), settings.replay_speed, (storagestream)->getLastSNs(), replay_time_col);
-            replay_step->setStepDescription("Replay Stream");
+                query_plan.getCurrentDataStream(), settings.replay_speed, std::move(last_sns), settings.replay_time_column);
```
Comment (yl-lisen) [inline src/Interpreters/InterpreterSelectQuery.cpp]: better parameters orders: `replay_speed, replay_time_column, last_sns`

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 9]
```diff
@@ -3867,6 +3839,45 @@ void InterpreterSelectQuery::checkUDA()
...
+            if (nested_storage)
+                storagestream = (*nested_storage)->as<StorageStream>();
+        }
+        else
+            storagestream = storage->as<StorageStream>();
+
+        if (!storagestream)
+            throw Exception("Replay Stream is only support append-only stream", ErrorCodes::NOT_IMPLEMENTED);
+    }
+    assert(storagestream);
```
Comment (yl-lisen) [inline src/Interpreters/InterpreterSelectQuery.cpp]: move this exception out of the `if` body

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 10]
```diff
@@ -3867,6 +3839,45 @@ void InterpreterSelectQuery::checkUDA()
...
+
+    const String & replay_time_col = settings.replay_time_column;
+    const auto & name_type = storage_snapshot->getColumn(GetColumnsOptions(GetColumnsOptions::All).withSubcolumns(), replay_time_col);
```
Comment (yl-lisen) [inline src/Interpreters/InterpreterSelectQuery.cpp]: GetColumnsOptions(GetColumnsOptions::All).withVirtuals()

Comment (yl-lisen) [reply src/Interpreters/InterpreterSelectQuery.cpp]: use `tryGetColumn` and check if it's exists

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 11]
```diff
@@ -3867,6 +3839,45 @@ void InterpreterSelectQuery::checkUDA()
...
+    const auto & type = name_type.type;
+    if (replay_time_col != ProtonConsts::RESERVED_APPEND_TIME && !isDateTime64(type))
+        throw Exception("Userdefined replay time column must be DateTime64", ErrorCodes::INVALID_SETTING_VALUE);
```
Comment (yl-lisen) [inline src/Interpreters/InterpreterSelectQuery.cpp]: `The setting `replay_time_column` must be DateTime32 or DateTime64`

Comment (yl-lisen) [reply src/Interpreters/InterpreterSelectQuery.cpp]: support DateTime64 and DateTime32

File: src/Interpreters/InterpreterSelectQuery.cpp [hunk 12]
```diff
@@ -3856,17 +3856,20 @@ std::vector<nlog::RecordSN> InterpreterSelectQuery::checkReplaySettingsAndGetLas
...
 
     const String & replay_time_col = settings.replay_time_column;
-    const auto & name_type = storage_snapshot->getColumn(GetColumnsOptions(GetColumnsOptions::All).withSubcolumns(), replay_time_col);
-    const auto & type = name_type.type;
-    if (replay_time_col != ProtonConsts::RESERVED_APPEND_TIME && !isDateTime64(type))
-        throw Exception("Userdefined replay time column must be DateTime64", ErrorCodes::INVALID_SETTING_VALUE);
+
+    auto name_type = storage_snapshot->tryGetColumn(GetColumnsOptions(GetColumnsOptions::All).withVirtuals(), replay_time_col);
+    if (!name_type.has_value())
+        throw Exception("Not found replay column in stream", ErrorCodes::INVALID_SETTING_VALUE);
```
Comment (yl-lisen) [inline src/Interpreters/InterpreterSelectQuery.cpp]: add replay_time_col name in error message

**Review by yl-lisen — APPROVED** [review]
