### PR TITLE
fix sql format

### LINKED ISSUE #278: parser error in array join with tp_delta
**Describe what's wrong**
with proton v1.3.19 and below sql, got an error.

`array join _tp_delta_col as _tp_delta`
-> `ARRAY JOIN_tp_delta_col AS _tp_delta`
```
nuc :) CREATE STREAM stream1 (device array(int8))

CREATE STREAM stream1
(`device` array(int8)
)

Query id: b844ef4c-3f1d-4059-8fab-f4b0cbd4b5fa

Ok.

0 rows in set. Elapsed: 0.084 sec. 

nuc :) CREATE MATERIALIZED VIEW `view1`  AS with cte as (   select     device as _tp_delta_col from stream1 ) select     _tp_delta   from cte array join _tp_delta_col as _tp_delta

CREATE MATERIALIZED VIEW view1 AS
WITH cte AS
  (
    SELECT 
      device AS _tp_delta_col
    FROM 
      stream1
  )
SELECT 
  _tp_delta
FROM 
  cte
ARRAY JOIN_tp_delta_col AS _tp_delta

Query id: 0b575b71-b671-46de-8689-b9333e1aa46a

Ok.

0 rows in set. Elapsed: 0.093 sec. 

nuc :) q
Bye.
~/io$ curl http://localhost:3218/proton/v1/ddl/streams
{"code":62,"error_msg":"Code: 62. DB::Exception: Syntax error: failed at position 432 ('JOIN_tp_delta_col') (line 15, col 7): JOIN_tp_delta_col AS _tp_delta. Expected one of: JOIN, end of query. (SYNTAX_ERROR) (version 1.3.19)","request_id":""}
~/io$ 

```

**How to reproduce**

**Error message and/or stacktrace**
```
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x19b9fb39 in /io/proton-v1.3.19-Linux-x86_64
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xfd109fa in /io/proton-v1.3.19-Linux-x86_64
2. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long, unsigned long) @ 0x17bd85c4 in /io/proton-v1.3.19-Linux-x86_64
3. DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned long, unsigned long) @ 0x17bd8660 in /io/proton-v1.3.19-Linux-x86_64
4. DB::parseQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1541e2cc in /io/proton-v1.3.19-Linux-x86_64
5. DB::TabularTableRestRouterHandler::buildTablesJSON(Poco::JSON::Object&, std::__1::vector<std::__1::shared_ptr<DB::TableRestRouterHandler::Table>, std::__1::allocator<std::__1::shared_ptr<DB::TableRestRouterHandler::Table>>> const&) const @ 0x15e5ad61 in /io/proton-v1.3.19-Linux-x86_64
6. DB::TableRestRouterHandler::executeGet(Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object>> const&) const @ 0x15e4e473 in /io/proton-v1.3.19-Linux-x86_64
7. DB::RestRouterHandler::execute(Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object>> const&) const @ 0x15e33956 in /io/proton-v1.3.19-Linux-x86_64
8. DB::RestRouterHandler::execute(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x15e32c6a in /io/proton-v1.3.19-Linux-x86_64
9. DB::RestHTTPRequestHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x15bfa1a2 in /io/proton-v1.3.19-Linux-x86_64
10. DB::RestHTTPRequestHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x15bf872d in /io/proton-v1.3.19-Linux-x86_64
11. DB::HTTPServerConnection::run() @ 0x15c176b2 in /io/proton-v1.3.19-Linux-x86_64
12. Poco::Net::TCPServerConnection::start() @ 0x19a8f1c7 in /io/proton-v1.3.19-Linux-x86_64
13. Poco::Net::TCPServerDispatcher::run() @ 0x19a8f6a5 in /io/proton-v1.3.19-Linux-x86_64
14. Poco::PooledThread::run() @ 0x19bff687 in /io/proton-v1.3.19-Linux-x86_64
15. Poco::ThreadImpl::runnableEntry(void*) @ 0x19bfd222 in /io/proton-v1.3.19-Linux-x86_64
16. ? @ 0x7f0abd536609 in ?
17. clone @ 0x7f0abd44b133 in ?
 (version 1.3.19)
```
**Additional context**

### PR DESCRIPTION
**Pull request by yl-lisen**
fix #278

### CODE REVIEW

File: src/Parsers/IAST.h [hunk 1]
```diff
@@ -224,6 +227,7 @@ class IAST : public std::enable_shared_from_this<IAST>, public TypePromotion<IAS
         bool need_parens = false;
         bool expression_list_always_start_on_new_line = false;  /// Line feed and indent before expression list even if it's of single element.
         bool expression_list_prepend_whitespace = false; /// Prepend whitespace (if it is required)
+        bool expression_list_elements_are_always_on_one_line = false;  /// proton: added
```
Comment (sunset3000) [inline src/Parsers/IAST.h:230]: please use "proton: starts" and "proton: ends". follow the code convention.

File: src/Parsers/ASTWithElement.cpp [hunk 2]
```diff
@@ -16,9 +16,7 @@ ASTPtr ASTWithElement::clone() const
 
 void ASTWithElement::formatImpl(const FormatSettings & settings, FormatState & state, FormatStateStacked frame) const
 {
-    /// proton: starts
-    std::string indent_str = settings.one_line ? "" : std::string(2 * frame.indent, ' ');
-    /// proton: ends
+    std::string indent_str = settings.one_line ? "" : std::string(settings.indent_size * frame.indent, ' '); /// proton: updated
```
Comment (sunset3000) [inline src/Parsers/ASTWithElement.cpp]: Please use "proton: starts" and "proton: ends".

File: src/Parsers/ASTWatchQuery.h [hunk 3]
```diff
@@ -40,7 +40,7 @@ class ASTWatchQuery : public ASTQueryWithTableAndOutput
 protected:
     void formatQueryImpl(const FormatSettings & s, FormatState & state, FormatStateStacked frame) const override
     {
-        std::string indent_str = s.one_line ? "" : std::string(4 * frame.indent, ' ');
+        std::string indent_str = s.one_line ? "" : std::string(s.indent_size * frame.indent, ' '); /// proton: updated
```
Comment (sunset3000) [inline src/Parsers/ASTWatchQuery.h]: Please use "proton: starts" and "proton: ends".

File: src/Parsers/ASTSubquery.cpp [hunk 4]
```diff
@@ -42,9 +42,7 @@ void ASTSubquery::formatImplWithoutAlias(const FormatSettings & settings, Format
         return;
     }
 
-    /// proton: starts
-    std::string indent_str = settings.one_line ? "" : std::string(2u * frame.indent, ' ');
-    /// proton: ends
+    std::string indent_str = settings.one_line ? "" : std::string(settings.indent_size * frame.indent, ' '); /// proton: updated
```
Comment (sunset3000) [inline src/Parsers/ASTSubquery.cpp]: Please use "proton: starts" and "proton: ends".

File: src/Parsers/ASTTableOverrides.cpp [hunk 5]
```diff
@@ -44,7 +44,7 @@ void ASTTableOverride::formatImpl(const FormatSettings & settings_, FormatState
         ++override_frame.indent;
         settings.ostr << nl_or_ws << '(' << nl_or_nothing;
     }
-    String indent_str = settings.one_line ? "" : String(4 * override_frame.indent, ' ');
+    String indent_str = settings.one_line ? "" : String(settings.indent_size * override_frame.indent, ' '); /// proton: updated
```
Comment (sunset3000) [inline src/Parsers/ASTTableOverrides.cpp]: Please use "proton: starts" and "proton: ends".

File: src/Parsers/ASTSelectWithUnionQuery.cpp [hunk 6]
```diff
@@ -42,7 +40,7 @@ void ASTSelectWithUnionQuery::formatQueryImpl(const FormatSettings & settings, F
             return "INTERSECT";
         else if (mode == SelectUnionMode::EXCEPT)
             return "EXCEPT";
-        return "";
+        return "UNION"; /// proton: updated
```
Comment (sunset3000) [inline src/Parsers/ASTSelectWithUnionQuery.cpp]: Please use "proton: starts" and "proton: ends".

File: src/Parsers/ASTExpressionList.cpp [hunk 7]
```diff
@@ -14,7 +14,7 @@ ASTPtr ASTExpressionList::clone() const
 
 void ASTExpressionList::formatImpl(const FormatSettings & settings, FormatState & state, FormatStateStacked frame) const
 {
-    if (frame.expression_list_prepend_whitespace && !settings.one_line )
+    if (frame.expression_list_prepend_whitespace)
```
Comment (sunset3000) [inline src/Parsers/ASTExpressionList.cpp:17]: please quote the changes with  "proton: starts" and "proton: ends"

**Review by sunset3000 — APPROVED** [review]
