### PR TITLE
fix: cannot load kafka external streams created before sharding_expr feature

### LINKED ISSUE #326: Fail to upgrade from 1.3.15-rc to 1.3.24-rc
**Describe what's wrong**

On demo.timeplus.cloud, I tried to upgrade it from 1.3.15-rc to 1.3.24-rc but proton failed to start. Here is the log

> 2023.11.22 22:12:51.688757 [ 2025 ] {} <Information> default.bookings (c18107f8-9e15-4569-953f-f02124c1e363): Load committed sn=16934043 for shard=0 from path=store/c18107f8-9e15-4569-953f-f02124c1e363/0/
> 2023.11.22 22:12:51.689303 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 36. DB::Exception: ExternalStream requires sharding key expression: Cannot attach stream `default`.`car_live_data_ext` from metadata file /var/lib/proton/store/c75aa40f-5da3-4f48-84b6-d3fc4dd806ae/car_live_data_ext.sql from query ATTACH STREAM default.car_live_data_ext UUID 'e88a76d8-390e-429c-8bba-9fac72422d2a' (`raw` string) ENGINE = ExternalStream SETTINGS type = 'kafka', brokers = 'kafka.user-gang:9092', topic = 'car_live_data'. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x19ed0379 in /usr/bin/proton
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, bool) @ 0xff3e65a in /usr/bin/proton
> 2. std::__1::shared_ptr<DB::IStorage> std::__1::__function::__policy_invoker<std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerStorageExternalStream(DB::StorageFactory&)::$_0, std::__1::shared_ptr<DB::IStorage> (DB::StorageFactory::Arguments const&)>>(std::__1::__function::__policy_storage const*, DB::StorageFactory::Arguments const&) @ 0x199ab97f in /usr/bin/proton
> 3. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15ae75e5 in /usr/bin/proton
> 4. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x14ebec2b in /usr/bin/proton
> 5. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, bool) @ 0x14ed9921 in /usr/bin/proton
> 6. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::TablesLoader::startLoadingIndependentTables(ThreadPoolImpl<ThreadFromGlobalPool>&, unsigned long)::$_0, void ()>>(std::__1::__function::__policy_storage const*) @ 0x14ee7d52 in /usr/bin/proton
> 7. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xffd4a21 in /usr/bin/proton
> 8. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xffd7588 in /usr/bin/proton
> 9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xffd31a8 in /usr/bin/proton
> 10. void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, long, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0xffd562e in /usr/bin/proton
> 11. ? @ 0x7f46f353d609 in ?
> 12. clone @ 0x7f46f3452133 in ?
>  (version 1.3.24)
> 
> 2023.11.22 22:12:52.743224 [ 1 ] {} <Information> RaftInstance: raft_server shutdown completed.
> 2023.11.22 22:12:52.743324 [ 90 ] {} <Error> RaftInstance: failed to accept a rpc connection due to error 125, Operation canceled
> 2023.11.22 22:12:53.001394 [ 1 ] {} <Error> Application: DB::Exception: ExternalStream requires sharding key expression: Cannot attach stream `default`.`car_live_data_ext` from metadata file /var/lib/proton/store/c75aa40f-5da3-4f48-84b6-d3fc4dd806ae/car_live_data_ext.sql from query ATTACH STREAM default.car_live_data_ext UUID 'e88a76d8-390e-429c-8bba-9fac72422d2a' (`raw` string) ENGINE = ExternalStream SETTINGS type = 'kafka', brokers = 'kafka.user-gang:9092', topic = 'car_live_data'
> 2023.11.22 22:12:53.001415 [ 1 ] {} <Information> Application: shutting down
> 2023.11.22 22:12:53.001635 [ 32 ] {} <Information> BaseDaemon: Stop SignalListener thread

### PR DESCRIPTION
**Pull request by zliang-min**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

The `sharding_expr` engine argument is supposed to be optional, however, the loading an stream created before this feature would crash proton.

fixes #326

### CODE REVIEW

**Review by yl-lisen — APPROVED** [review]
LGTM

File: src/Storages/ExternalStream/Kafka/Kafka.h [hunk 1]
```diff
@@ -42,7 +42,8 @@ class Kafka final : public StorageExternalStreamImpl
     const String & password() const { return settings->password.value; }
     const String & sslCaCertFile() const { return settings->ssl_ca_cert_file.value; }
     const klog::KConfParams & properties() const { return kafka_properties; }
-    const ASTPtr & partitioning_expr_ast() const { return partitioning_expr; }
+    bool has_custom_partitioning_expr() const { return !engine_args.empty(); }
```
Comment (chenziliang) [inline src/Storages/ExternalStream/Kafka/Kafka.h]: Let's use camelCase convention

Comment (chenziliang) [reply src/Storages/ExternalStream/Kafka/Kafka.h]: Is partitioning expr meaning sharding expression, if yes, please use sharding expression consitently since partition in Proton database is totally different.

Comment (chenziliang) [reply src/Storages/ExternalStream/Kafka/Kafka.h]:
```
hasShardingExpr() ...
shardingExprAst() ...
```

File: src/Storages/ExternalStream/Kafka/KafkaSink.cpp [hunk 2]
```diff
@@ -24,9 +24,15 @@ extern const int TYPE_MISMATCH;
 
 namespace KafkaStream
 {
+void ChunkPartitioner::use_random_paritioning()
```
Comment (chenziliang) [inline src/Storages/ExternalStream/Kafka/KafkaSink.cpp]: camelCase style please

File: src/Storages/ExternalStream/Kafka/Kafka.h (hunk 1 above)
Comment (zliang-min) [reply src/Storages/ExternalStream/Kafka/Kafka.h]: I use partition/partitioning in the context of Kafka, and shard/sharding in other places. This is because all Kafka APIs use partition not shard. Do you still think we should use shard even in the context of Kafka?

Comment (chenziliang) [reply src/Storages/ExternalStream/Kafka/Kafka.h]: I prefer sharding everywhere.

File: src/Storages/ExternalStream/Kafka/KafkaSink.h [hunk 3]
```diff
@@ -19,26 +19,26 @@ namespace DB
 
 namespace KafkaStream
 {
-/// Partition Chunk's to paritions (i.e. shards) by the partitioning expression.
-class ChunkPartitioner
+/// Shard Chunk's to shards (or partitions in Kafka's term) by the sharding expression.
+class ChunkSharder
```
Comment (chenziliang) [inline src/Storages/ExternalStream/Kafka/KafkaSink.h:23]: Now we can refactor it out and reuse it for StorageStream as well in the next PR.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
