### PR TITLE
fix incorrect subscribe mode check for internal subquery

### LINKED ISSUE #498: CREATE MATERIALIZED VIEW Failed for streaming query
**Describe what's wrong**

```sql
create stream dim_t(id int, type int);
create stream vk(id int, value float) primary key id settings mode='versioned_kv';
create materialized view mv as with list as (select id from table(dim_t)) select id, value from vk where id in list;
```
**But got exception:**
Received exception from server (version 1.3.31):
Code: 48. DB::Exception: Received from localhost:8463. DB::Exception: SUBSCRIBE can only work with streaming query. (NOT_IMPLEMENTED)

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by yl-lisen**
Fix #498

### CODE REVIEW

File: src/Processors/QueryPlan/QueryPlan.cpp [hunk 1]
```diff
@@ -198,8 +198,6 @@ QueryPipelineBuilderPtr QueryPlan::buildQueryPipeline(
     last_pipeline->addResources(std::move(resources));
 
     /// proton : starts
-    last_pipeline->setExecuteMode(queryExecuteMode(isStreaming(), query_context->getSettingsRef()));
-
```
Comment (yl-lisen) [inline src/Processors/QueryPlan/QueryPlan.cpp:202]: already exists `setExecuteMode` in src/Interpreters/InterpreterSelectWithUnionQuery.cpp:403

**Review by sunset3000 — APPROVED** [review]
