### PR TITLE
Bugfix/issue-770-log-stream-analysis

### LINKED ISSUE #770: Log-Stream-Analysis: Unable to Read Logs from Multiple Files
**Describe what's wrong**

The Log-Stream-Analysis functionality is only processing logs from the most recently modified file, instead of all specified log files.

**How to reproduce**
1. Create an external stream for file logs using the following SQL command:
    ```sql
    CREATE EXTERNAL STREAM proton_log
    (
       `raw` string,
       `timeStamp` ALIAS to_time(extract(raw, '^(\\d{4}\\.\\d{2}\\.\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d+)')),
       `level` ALIAS extract(raw, '} <(\\w+)>'),
       `message` ALIAS extract(raw, '} <\\w+> (.*)')
    )
    SETTINGS
       type = 'log',
       log_files = 'proton*\\.log',
       log_dir = '/path',
       row_delimiter = '(\\d{4}\\.\\d{2}\\.\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d+) \\[ \\d+ \\] \\{',
       timestamp_regex = '^(\\d{4}\\.\\d{2}\\.\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d+)'
    ```

2. Run the following query:
    ```sql
    SELECT timeStamp, level, message FROM proton_log
    ```

3. Observe that only the latest log file is being analyzed.

**Error message and/or stacktrace**

**Additional context**

---

### PR DESCRIPTION
**Pull request by chhtimeplus**
PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

### CODE REVIEW

File: src/Storages/ExternalStream/BreakLines.cpp [hunk 1]
```diff
@@ -43,10 +41,9 @@ std::vector<std::string_view> breakLines(const char * data, size_t & length, con
             }
             else
             {
-                /// [data in the middle][breaker][next start...][breaker][next start...
-                /// data in the middle + breaker are composed into a line
-                lines.emplace_back(last_input.data(), static_cast<size_t>(input.data() - last_input.data()));
-                last_input = input;
+                /// Force the prefix information into a line; there may be some configuration messages
```
Comment (sunset3000) [inline src/Storages/ExternalStream/BreakLines.cpp]: Do not remove the previous comments. you can add your new comment here.

File: src/Storages/ExternalStream/Log/FileLog.cpp [hunk 2]
```diff
@@ -130,21 +130,21 @@ FileLogSource::FileContainer FileLog::searchForCandidates()
             if (file_regex->Match(filename, 0, filename.size(), re2::RE2::ANCHOR_BOTH, nullptr, 0))
             {
                 auto last_modified = lastModifiedTime(dir_entry.path());
-                if (last_modified >= start_timestamp)
-                    candidates.emplace(last_modified, std::filesystem::canonical(dir_entry.path()));
+                // Add all candidates, not just the most recently modified ones
```
Comment (sunset3000) [inline src/Storages/ExternalStream/Log/FileLog.cpp]: missing a '/' character.

File: src/Storages/ExternalStream/Log/FileLog.cpp [hunk 3]
```diff
@@ -130,21 +130,21 @@ FileLogSource::FileContainer FileLog::searchForCandidates()
...
     }
 
-    if (start_timestamp == nlog::LATEST_SN)
-    {
-        /// Tail the log last file
-        /// Remove all other files except the last one
-        for (; !candidates.empty() && candidates.size() != 1;)
-            candidates.erase(candidates.begin());
-    }
+    // if (start_timestamp == nlog::LATEST_SN)
```
Comment (sunset3000) [inline src/Storages/ExternalStream/Log/FileLog.cpp]: There are two scenarios to be implemented:
a) streaming query: use the latest file to tail
b) historic query: use all files to query

File: src/Storages/ExternalStream/tests/gtest_linebreaker.cpp [hunk 4]
```diff
@@ -33,10 +33,10 @@ TEST(BreakLines, BreakLinesAtBeginning)
 
 TEST(BreakLines, BreakLinesAtEnd)
 {
-    std::string line1{"2022.04.14 18:04:43.028648 [ 4273 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 2 databases in 0.000351319 sec\n"};
-    std::string line2{"2022.04.14 18:04:43.028801 [ 4273 ] {} <Information> DatabaseAtomic (default): Starting up tables.\n"};
+    std::string line1{"INFO: 2022.04.14 18:04:43.028648 [ 4273 ] {} <Information> TablesLoader: Parsed metadata of 0 tables in 2 databases in 0.000351319 sec"};
```
Comment (sunset3000) [inline src/Storages/ExternalStream/tests/gtest_linebreaker.cpp]: Can you use the previous sample (i.e. logs of proton)?

**Review by sunset3000 — APPROVED** [review]
